name: himate_frontend
description: HIMATE System control plane.
publish_to: none
version: 0.2.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.2.2
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
    - assets/himate_heritage.svg
