#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]

def read(path: str) -> str:
    return (ROOT / path).read_text()

def require(ok: bool, message: str) -> None:
    if not ok:
        print("FAIL:", message)
        sys.exit(1)

common = read("services/internal/common/common.go")
serviceauth = read("services/internal/serviceauth/contract.go")
serviceauth_tests = read("services/internal/serviceauth/contract_test.go")
automation = read("services/internal/automation/contract.go")
payments = read("services/cmd/payments/main.go")
payment_tests = read("services/cmd/payments/main_test.go")
secrets = read("services/cmd/gateway/platform_secrets.go")
secret_tests = read("services/internal/common/secrets_test.go")
render = read("render.yaml")
gitignore = read(".gitignore")

# Platform secrets are encrypted and never read back through the admin surface.
require("EncryptPlatformSecret" in secrets,
        "platform secret vault no longer encrypts values before persistence")
require('"values_readable": false' in secrets,
        "platform secret metadata no longer declares write-only values")
require('"value": nil' in secrets,
        "platform secret metadata may expose secret values")
require("TestPlatformSecretRejectsWrongMaster" in secret_tests,
        "platform secret authenticated-encryption regression test is missing")
require(".env" in gitignore,
        "local environment secret files are not ignored")

# Render keeps externally supplied credentials out of source-controlled literal values.
for key in [
    "STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET", "RENDER_API_KEY",
    "HIMATE_CONNECTOR_DATA_MASTER_KEY_B64", "PARTNER_DATABASE_ADMIN_URL",
    "SMTP_PASSWORD",
]:
    require(f"key: {key}" in render, f"Render secret contract missing: {key}")
require("key: HIMATE_AUTOMATION_FINANCE_SECRET" in render and "generateValue: true" in render,
        "automation finance identity secret is not generated by Render")

# Internal control-plane routes use timestamped HMAC service identity.
require("func Sign(" in serviceauth and "func Verify(" in serviceauth,
        "internal service HMAC identity contract is missing")
require("subtle.ConstantTimeCompare" in serviceauth,
        "internal service signatures are not compared in constant time")
require("delta > maxSkew" in serviceauth,
        "internal service signatures do not enforce timestamp freshness")
require("authority header tampering" in serviceauth_tests.lower(),
        "internal authority-header tampering regression proof is missing")
require("serviceauth.Verify" in common and 'strings.HasPrefix(r.URL.Path, "/internal/v1/")' in common,
        "signed identity is not enforced at the internal route boundary")

# Automation uses a separate body-bound service identity contract.
require("bodyHash(body)" in automation and "subtle.ConstantTimeCompare" in automation,
        "automation service identity is not bound to the request body")
require("service identity signature expired" in automation,
        "automation signatures do not enforce replay time tolerance")

# Stripe webhook integrity and replay defenses.
require("verifyStripeSignature(raw" in payments,
        "Stripe webhook signature verification is missing")
require("5*time.Minute" in payments,
        "Stripe webhook signature tolerance is missing")
require("payload_sha256" in payments and "WEBHOOK_EVENT_CONFLICT" in payments,
        "Stripe webhook event-ID/payload replay conflict protection is missing")
require('status == "PROCESSED"' in payments and '"status":"duplicate"' in payments.replace(" ", ""),
        "processed Stripe webhook replay is not idempotent")
require("PAYMENT_AMOUNT_MISMATCH" in payments and "PAYMENT_ID_MISMATCH" in payments,
        "verified webhook is not reconciled against original payment identity/amount")
require("TestStripeSignatureVerification" in payment_tests,
        "Stripe webhook signature regression test is missing")

print("START-24.5 secrets/service-identity/webhook acceptance: PASS")
