part of 'main.dart';

const himateSupportedLocales = <Locale>[
  Locale('en', 'US'),
  Locale('hu', 'HU'),
];

Locale himateLocaleFromCode(String? code) {
  switch ((code ?? '').trim()) {
    case 'hu_HU':
      return const Locale('hu', 'HU');
    default:
      return const Locale('en', 'US');
  }
}

String himateLocaleCode(Locale locale) =>
    locale.languageCode.toLowerCase() == 'hu' ? 'hu_HU' : 'en_US';

String tr(BuildContext context, String key) =>
    HimateI18n.text(himateLocaleCode(Localizations.localeOf(context)), key);


class LText extends StatelessWidget {
  const LText(
    this.data, {
    super.key,
    this.style,
    this.strutStyle,
    this.textAlign,
    this.textDirection,
    this.locale,
    this.softWrap,
    this.overflow,
    this.textScaler,
    this.maxLines,
    this.semanticsLabel,
    this.textWidthBasis,
    this.textHeightBehavior,
    this.selectionColor,
  });

  final String data;
  final TextStyle? style;
  final StrutStyle? strutStyle;
  final TextAlign? textAlign;
  final TextDirection? textDirection;
  final Locale? locale;
  final bool? softWrap;
  final TextOverflow? overflow;
  final TextScaler? textScaler;
  final int? maxLines;
  final String? semanticsLabel;
  final TextWidthBasis? textWidthBasis;
  final TextHeightBehavior? textHeightBehavior;
  final Color? selectionColor;

  @override
  Widget build(BuildContext context) {
    final code = himateLocaleCode(Localizations.localeOf(context));
    return material.Text(
      HimateI18n.literal(code, data),
      style: style,
      strutStyle: strutStyle,
      textAlign: textAlign,
      textDirection: textDirection,
      locale: locale,
      softWrap: softWrap,
      overflow: overflow,
      textScaler: textScaler,
      maxLines: maxLines,
      semanticsLabel: semanticsLabel,
      textWidthBasis: textWidthBasis,
      textHeightBehavior: textHeightBehavior,
      selectionColor: selectionColor,
    );
  }
}

String uiLiteralFor(BuildContext context, String value) =>
    HimateI18n.literal(himateLocaleCode(Localizations.localeOf(context)), value);

String uiLiteral(String value) => HimateI18n.literal(HimateI18n.activeLocale, value);

class HimateI18n {
  static String activeLocale = 'en_US';

  static const Map<String, Map<String, String>> _values = {
    'en_US': {
      'account': 'Account',
      'profile': 'Profile',
      'signOut': 'Sign out',
      'language': 'Language',
      'englishUS': 'English (US)',
      'hungarian': 'Magyar',
      'fullName': 'Full name',
      'jobTitle': 'Job title',
      'phone': 'Phone',
      'timezone': 'Time zone',
      'saveChanges': 'Save changes',
      'profileUpdated': 'Profile updated',
      'profileIntro': 'Personal settings for your HIMATE account.',
      'systemOwner': 'System Owner',
      'systemOwnerHint': 'This account can create users and manage access.',
      'roles': 'Roles',
      'passwordSecurity': 'Password & security',
      'currentPassword': 'Current password',
      'newPassword': 'New password',
      'confirmPassword': 'Confirm new password',
      'changePassword': 'Change password',
      'passwordChanged': 'Password changed. Other sessions were invalidated.',
      'passwordsMismatch': 'The new passwords do not match.',
      'passwordMin': 'Use at least 12 characters.',
      'passwordPolicy': 'Use at least 12 characters with lowercase, uppercase, a number and a special character.',
      'cancel': 'Cancel',
      'close': 'Close',
      'welcomeBack': 'Welcome back',
      'signInSubtitle': 'Sign in to your HIMATE System account',
      'emailAddress': 'Email address',
      'password': 'Password',
      'rememberMe': 'Remember me',
      'forgotPassword': 'Forgot password?',
      'signIn': 'Sign in',
      'showPassword': 'Show password',
      'hidePassword': 'Hide password',
      'enterCredentials': 'Enter your administrator email and password.',
      'resetRequestTitle': 'Reset your password',
      'resetRequestBody': 'Enter your administrator email. If the account exists, a one-time reset link will be sent.',
      'resetSend': 'Send reset link',
      'resetSent': 'If the account exists, password reset instructions have been sent.',
      'resetNewPasswordTitle': 'Set a new password',
      'resetNewPassword': 'New password',
      'resetConfirmPassword': 'Confirm new password',
      'resetConfirmAction': 'Update password',
      'resetMismatch': 'The two passwords do not match.',
      'resetDone': 'Your password has been updated. Sign in with the new password.',
      'nav.dashboard': 'Dashboard',
      'nav.dashboardSub': 'Platform overview',
      'nav.partners': 'Partners',
      'nav.partnersSub': 'Partner control',
      'nav.finance': 'Licensing & Finance',
      'nav.financeSub': 'Commercial management',
      'nav.impact': 'Impact & Reports',
      'nav.impactSub': 'Metrics and reporting',
      'nav.website': 'Website & Marketing',
      'nav.websiteSub': 'Brand and growth',
      'nav.system': 'System & Operations',
      'nav.systemSub': 'Infrastructure health',
      'nav.admin': 'Administration',
      'nav.adminSub': 'Roles and control',
    },
    'hu_HU': {
      'account': 'Fiók',
      'profile': 'Profil',
      'signOut': 'Kijelentkezés',
      'language': 'Nyelv',
      'englishUS': 'Angol (USA)',
      'hungarian': 'Magyar',
      'fullName': 'Teljes név',
      'jobTitle': 'Munkakör',
      'phone': 'Telefonszám',
      'timezone': 'Időzóna',
      'saveChanges': 'Módosítások mentése',
      'profileUpdated': 'Profil frissítve',
      'profileIntro': 'A HIMATE-fiók személyes beállításai.',
      'systemOwner': 'Rendszertulajdonos',
      'systemOwnerHint': 'Ez a fiók hozhat létre felhasználókat és kezelheti a hozzáféréseket.',
      'roles': 'Szerepkörök',
      'passwordSecurity': 'Jelszó és biztonság',
      'currentPassword': 'Jelenlegi jelszó',
      'newPassword': 'Új jelszó',
      'confirmPassword': 'Új jelszó megerősítése',
      'changePassword': 'Jelszó módosítása',
      'passwordChanged': 'A jelszó megváltozott. A többi munkamenet érvénytelenítve lett.',
      'passwordsMismatch': 'Az új jelszavak nem egyeznek.',
      'passwordMin': 'Legalább 12 karakter szükséges.',
      'passwordPolicy': 'Használj legalább 12 karaktert, kis- és nagybetűt, számot és speciális karaktert.',
      'cancel': 'Mégse',
      'close': 'Bezárás',
      'welcomeBack': 'Üdv újra',
      'signInSubtitle': 'Jelentkezz be a HIMATE System fiókodba',
      'emailAddress': 'E-mail-cím',
      'password': 'Jelszó',
      'rememberMe': 'Maradjak bejelentkezve',
      'forgotPassword': 'Elfelejtetted a jelszót?',
      'signIn': 'Bejelentkezés',
      'showPassword': 'Jelszó megjelenítése',
      'hidePassword': 'Jelszó elrejtése',
      'enterCredentials': 'Add meg az adminisztrátori e-mail-címedet és jelszavadat.',
      'resetRequestTitle': 'Jelszó visszaállítása',
      'resetRequestBody': 'Add meg az adminisztrátori e-mail-címedet. Ha a fiók létezik, egyszer használható visszaállítási linket küldünk.',
      'resetSend': 'Visszaállítási link küldése',
      'resetSent': 'Ha a fiók létezik, elküldtük a jelszó-visszaállítási útmutatót.',
      'resetNewPasswordTitle': 'Új jelszó beállítása',
      'resetNewPassword': 'Új jelszó',
      'resetConfirmPassword': 'Új jelszó megerősítése',
      'resetConfirmAction': 'Jelszó frissítése',
      'resetMismatch': 'A két jelszó nem egyezik.',
      'resetDone': 'A jelszavad frissült. Jelentkezz be az új jelszóval.',
      'nav.dashboard': 'Irányítópult',
      'nav.dashboardSub': 'Platform áttekintése',
      'nav.partners': 'Partnerek',
      'nav.partnersSub': 'Partnerkezelés',
      'nav.finance': 'Licencelés és pénzügy',
      'nav.financeSub': 'Kereskedelmi kezelés',
      'nav.impact': 'Hatás és jelentések',
      'nav.impactSub': 'Mérőszámok és riportok',
      'nav.website': 'Weboldal és marketing',
      'nav.websiteSub': 'Márka és növekedés',
      'nav.system': 'Rendszer és üzemeltetés',
      'nav.systemSub': 'Infrastruktúra állapota',
      'nav.admin': 'Adminisztráció',
      'nav.adminSub': 'Szerepkörök és kontroll',
    },
  };


  static const Map<String, String> _literalHu = <String, String>{
    'Dashboard': 'Irányítópult',
    'Partners': 'Partnerek',
    'Partner': 'Partner',
    'Licensing & Finance': 'Licencelés és pénzügy',
    'Impact & Reports': 'Hatás és jelentések',
    'Website & Marketing': 'Weboldal és marketing',
    'System & Operations': 'Rendszer és üzemeltetés',
    'Administration': 'Adminisztráció',
    'Welcome to HIMATE System': 'Üdvözlünk a HIMATE Systemben',
    'Manage partners, programs and cultural impact — all in one place.': 'Kezeld egy helyen a partnereket, programokat és a kulturális hatást.',
    'Manage partners, programs, and cultural impact — all in one place.': 'Kezeld egy helyen a partnereket, programokat és a kulturális hatást.',
    'Active Partners': 'Aktív partnerek',
    'Active Programs': 'Aktív programok',
    'Revenue (YTD)': 'Bevétel (YTD)',
    'People Reached': 'Elért emberek',
    'Recent Activity': 'Legutóbbi tevékenység',
    'Program Impact': 'Programhatás',
    'This Year': 'Idén',
    'View all': 'Összes megtekintése',
    'New partner registered': 'Új partner regisztrálva',
    'Program updated': 'Program frissítve',
    'Payment received': 'Fizetés beérkezett',
    'New user added': 'Új felhasználó hozzáadva',
    'Partner activity': 'Partnertevékenység',
    'Module catalog activity': 'Modulkatalógus-tevékenység',
    'Billing activity': 'Pénzügyi tevékenység',
    'Administration activity': 'Adminisztrációs tevékenység',
    'Partner portfolio': 'Partnerportfólió',
    'New Partner': 'Új partner',
    'Search partners...': 'Partnerek keresése...',
    'All categories': 'Minden kategória',
    'All lifecycle states': 'Minden életciklus-állapot',
    'All health states': 'Minden egészségi állapot',
    'Reference partner': 'Referenciapartner',
    'Reference partners': 'Referenciapartnerek',
    'Live partners': 'Élő partnerek',
    'Prospects': 'Érdeklődők',
    'Partner could not be opened': 'A partner nem nyitható meg',
    'Partner workspace unavailable': 'A partner munkaterülete nem érhető el',
    'Open workspace': 'Munkaterület megnyitása',
    'Partner Health': 'Partnerállapot',
    'Company Data': 'Cégadatok',
    'Company data': 'Cégadatok',
    'Finance & Documents': 'Pénzügy és dokumentumok',
    'Partner Modules': 'Partnermodulok',
    'Statistics': 'Statisztikák',
    'System & Environment': 'Rendszer és környezet',
    'Commercial terms': 'Kereskedelmi feltételek',
    'Commercial Rules': 'Kereskedelmi szabályok',
    'Commercial evidence and internal invoice records for this partner.': 'A partner kereskedelmi bizonyítékai és belső számlarekordjai.',
    'Legal name': 'Hivatalos cégnév',
    'Brand / DBA': 'Márkanév / DBA',
    'Registration number': 'Cégjegyzékszám',
    'Tax ID': 'Adóazonosító',
    'Primary contact': 'Elsődleges kapcsolattartó',
    'Primary email': 'Elsődleges e-mail',
    'Finance contact': 'Pénzügyi kapcsolattartó',
    'Finance email': 'Pénzügyi e-mail',
    'Technical contact': 'Technikai kapcsolattartó',
    'Technical email': 'Technikai e-mail',
    'Marketing contact': 'Marketing kapcsolattartó',
    'Marketing email': 'Marketing e-mail',
    'Country': 'Ország',
    'State / region': 'Állam / régió',
    'City': 'Város',
    'Postal code': 'Irányítószám',
    'Address line 1': 'Cím 1. sor',
    'Address line 2': 'Cím 2. sor',
    'Website': 'Weboldal',
    'Phone': 'Telefon',
    'Notes': 'Megjegyzések',
    'Edit partner': 'Partner szerkesztése',
    'Save changes': 'Módosítások mentése',
    'Lifecycle': 'Életciklus',
    'Lifecycle change reason': 'Életciklus-váltás indoka',
    'Module catalog': 'Modulkatalógus',
    'Canonical Module Catalog': 'Kanonikus modulkatalógus',
    'Search module catalog...': 'Keresés a modulkatalógusban...',
    'Search modules...': 'Modulok keresése...',
    'All groups': 'Minden csoport',
    'Availability': 'Elérhetőség',
    'Add custom module': 'Egyedi modul hozzáadása',
    'Add module': 'Modul hozzáadása',
    'Create module': 'Modul létrehozása',
    'Module name': 'Modul neve',
    'Module name *': 'Modul neve *',
    'Stable technical key': 'Stabil technikai kulcs',
    'Stable key *': 'Stabil kulcs *',
    'Menu group': 'Menücsoport',
    'Description': 'Leírás',
    'Default monthly price (USD)': 'Alap havi ár (USD)',
    'Default 30-day price': 'Alap 30 napos ár',
    'Visibility is separate from module code existence.': 'A láthatóság független a modul kódjának létezésétől.',
    'Module state': 'Modulállapot',
    'Visible for partner': 'Partner számára látható',
    'Included in base package': 'Alapcsomag része',
    'Partner 30-day price': 'Partner 30 napos ára',
    'Change reason': 'Módosítás indoka',
    'Price effective at': 'Ár érvényességének kezdete',
    'Cancel at period end': 'Lemondás az időszak végén',
    'Subscription lifecycle': 'Előfizetés életciklusa',
    'Cancellation effective': 'Lemondás hatálybalépése',
    'Cancel pending': 'Lemondás függőben',
    'Paid-period deactivation is Billing-managed. Use Cancel at period end; access remains active until the current 30-day period closes.': 'A kifizetett időszak kikapcsolását a számlázási rendszer kezeli. Használd az időszak végi lemondást; a hozzáférés az aktuális 30 napos időszak végéig aktív marad.',
    'Billing profile': 'Számlázási profil',
    'Edit billing profile': 'Számlázási profil szerkesztése',
    'Bank name': 'Bank neve',
    'Bank address': 'Bank címe',
    'Account number': 'Bankszámlaszám',
    'IBAN': 'IBAN',
    'SWIFT / BIC': 'SWIFT / BIC',
    'Save billing profile': 'Számlázási profil mentése',
    'Activation fee': 'Aktiválási díj',
    'Activation fee · USD': 'Aktiválási díj · USD',
    'Activation fee waived': 'Aktiválási díj elengedve',
    'Base monthly fee': 'Alap havi díj',
    'Base monthly fee · USD': 'Alap havi díj · USD',
    'Annual increase %': 'Éves emelés %',
    'Service activation / anchor date': 'Szolgáltatás aktiválási / horgonydátuma',
    'License status': 'Licenc állapota',
    'License paid': 'Licenc kifizetve',
    'Paid amount': 'Kifizetett összeg',
    'Payment date': 'Fizetés dátuma',
    'Payment reference': 'Fizetési hivatkozás',
    'Provider customer ID': 'Szolgáltatói ügyfélazonosító',
    'Payment method ID': 'Fizetési mód azonosítója',
    'Provider reference': 'Szolgáltatói hivatkozás',
    'Provider-backed payment': 'Szolgáltató által igazolt fizetés',
    'Automatic recurring collection': 'Automatikus ismétlődő díjbeszedés',
    'Collect activation license after save': 'Aktiválási licenc beszedése mentés után',
    'Stripe customer ID': 'Stripe ügyfélazonosító',
    'Saved payment method': 'Mentett fizetési mód',
    'Stripe customer ID, e.g. cus_...': 'Stripe ügyfélazonosító, pl. cus_...',
    'Saved payment method, e.g. pm_...': 'Mentett fizetési mód, pl. pm_...',
    'Recurring invoices are charged off-session through the configured provider.': 'Az ismétlődő számlákat a rendszer a konfigurált szolgáltatón keresztül, háttérben terheli.',
    'PAID is set only after the signed provider webhook is verified.': 'A PAID állapot csak az aláírt szolgáltatói webhook ellenőrzése után áll be.',
    'Use only where no provider transaction applies.': 'Csak akkor használd, ha nem tartozik hozzá szolgáltatói tranzakció.',
    'Payment authority': 'Fizetési jogosultság',
    'Signed provider webhook only': 'Kizárólag aláírt szolgáltatói webhook',
    'Automatic 30-day collection': 'Automatikus 30 napos díjbeszedés',
    'Opens only after verified PAID state': 'Csak ellenőrzött PAID állapot után nyílik meg',
    'Payment evidence': 'Fizetési bizonyíték',
    'English category name *': 'Angol kategórianév *',
    'Hungarian category name *': 'Magyar kategórianév *',
    'Hungarian category name': 'Magyar kategórianév',
    'English group name *': 'Angol csoportnév *',
    'Hungarian group name *': 'Magyar csoportnév *',
    'English module name *': 'Angol modulnév *',
    'Hungarian module name *': 'Magyar modulnév *',
    'English display label *': 'Angol megjelenítési név *',
    'Hungarian display label *': 'Magyar megjelenítési név *',
    'English role name *': 'Angol szerepkörnév *',
    'Hungarian role name *': 'Magyar szerepkörnév *',
    'English description': 'Angol leírás',
    'Hungarian description': 'Magyar leírás',
    'BILINGUAL IDENTITY': 'KÉTNYELVŰ AZONOSSÁG',
    'BILINGUAL ROLE IDENTITY': 'KÉTNYELVŰ SZEREPKÖR-AZONOSSÁG',
    'pl. Kulturális alapítvány': 'pl. Kulturális alapítvány',
    'Document name *': 'Dokumentum neve *',
    'Document type': 'Dokumentumtípus',
    'Storage URL / reference': 'Tárolási URL / hivatkozás',
    'Register document': 'Dokumentum rögzítése',
    'Invoices': 'Számlák',
    'Documents': 'Dokumentumok',
    'Impact Summary': 'Hatásösszesítő',
    'Metric Definitions': 'Mérőszám-definíciók',
    'New metric': 'Új mérőszám',
    'Metric key': 'Mérőszám kulcsa',
    'Unit': 'Mértékegység',
    'Aggregation': 'Aggregáció',
    'Scope': 'Hatókör',
    'Baseline': 'Bázisérték',
    'Baseline value': 'Bázisérték',
    'Baseline period start': 'Bázisidőszak kezdete',
    'Baseline period end': 'Bázisidőszak vége',
    'Set baseline': 'Bázisérték beállítása',
    'Save baseline': 'Bázisérték mentése',
    'Record impact value': 'Hatásérték rögzítése',
    'Record value': 'Érték rögzítése',
    'Numeric value': 'Számérték',
    'Period start': 'Időszak kezdete',
    'Period end': 'Időszak vége',
    'Source reference': 'Forráshivatkozás',
    'Evidence': 'Bizonyíték',
    'Evidence Library': 'Bizonyítéktár',
    'Upload Evidence': 'Bizonyíték feltöltése',
    'Create evidence': 'Bizonyíték létrehozása',
    'Evidence title *': 'Bizonyíték címe *',
    'Evidence type': 'Bizonyíték típusa',
    'Linked metric': 'Kapcsolt mérőszám',
    'Verification': 'Ellenőrzés',
    'Verified': 'Ellenőrzött',
    'Unverified': 'Nem ellenőrzött',
    'Rejected': 'Elutasított',
    'Uploaded': 'Feltöltve',
    'Uploaded by': 'Feltöltötte',
    'Verified by': 'Ellenőrizte',
    'Download': 'Letöltés',
    'Preview': 'Előnézet',
    'Reports': 'Jelentések',
    'Generate Report': 'Jelentés készítése',
    'Generate PDF report': 'PDF-jelentés készítése',
    'Report type': 'Jelentés típusa',
    'Report title': 'Jelentés címe',
    'Partner Impact Report': 'Partnerhatás-jelentés',
    'Multi-Partner Report': 'Többpartneres jelentés',
    'HIMATE Global Impact Report': 'HIMATE globális hatásjelentés',
    'Queue report': 'Jelentés sorba állítása',
    'Download PDF': 'PDF letöltése',
    'Regenerate snapshot': 'Pillanatkép újragenerálása',
    'HIMATE CMS': 'HIMATE CMS',
    'CMS Pages': 'CMS-oldalak',
    'Media Assets': 'Médiaelemek',
    'Upload media': 'Média feltöltése',
    'New CMS page': 'Új CMS-oldal',
    'Create draft': 'Vázlat létrehozása',
    'Edit draft': 'Vázlat szerkesztése',
    'Publish': 'Publikálás',
    'Published': 'Publikálva',
    'Draft': 'Vázlat',
    'Version history ·': 'Verzióelőzmények ·',
    'Audit': 'Audit',
    'Page key': 'Oldalkulcs',
    'Admin page name *': 'Adminoldal neve *',
    'Slug *': 'Slug *',
    'SEO title': 'SEO-cím',
    'SEO title * for publish': 'SEO-cím * publikáláshoz',
    'Meta description': 'Meta leírás',
    'Meta description * for publish': 'Meta leírás * publikáláshoz',
    'Canonical HTTPS URL': 'Kanonikus HTTPS URL',
    'Canonical HTTPS URL * for publish': 'Kanonikus HTTPS URL * publikáláshoz',
    'Open Graph title': 'Open Graph cím',
    'Open Graph description': 'Open Graph leírás',
    'Open Graph image': 'Open Graph kép',
    'Noindex': 'Noindex',
    'Content sections': 'Tartalmi szekciók',
    'Add section': 'Szekció hozzáadása',
    'Section ID *': 'Szekcióazonosító *',
    'Component type': 'Komponenstípus',
    'Heading * when visible': 'Címsor * ha látható',
    'Body': 'Törzsszöveg',
    'Media asset': 'Médiaelem',
    'CTA label': 'CTA felirat',
    'CTA URL': 'CTA URL',
    'Visible': 'Látható',
    'Move up': 'Mozgatás felfelé',
    'Move down': 'Mozgatás lefelé',
    'Remove from draft': 'Eltávolítás a vázlatból',
    'Contact Leads': 'Kapcsolati érdeklődők',
    'Contact lead': 'Kapcsolati érdeklődő',
    'Search leads': 'Érdeklődők keresése',
    'Lead status': 'Érdeklődő állapota',
    'All statuses': 'Minden állapot',
    'Assigned to': 'Felelős',
    'Name or team': 'Név vagy csapat',
    'Name, organization, email or message': 'Név, szervezet, e-mail vagy üzenet',
    'Inquiry': 'Megkeresés',
    'Internal follow-up note': 'Belső utánkövetési jegyzet',
    'Record next step, outcome or context': 'Rögzítsd a következő lépést, eredményt vagy kontextust',
    'Save lead': 'Érdeklődő mentése',
    'No contact leads': 'Nincsenek kapcsolati érdeklődők',
    'New website inquiries will appear here automatically.': 'Az új weboldali megkeresések automatikusan itt jelennek meg.',
    'Contact Leads unavailable': 'A kapcsolati érdeklődők nem érhetők el',
    'Website inquiries stored in HIMATE with follow-up status, owner and internal notes.': 'A weboldali megkeresések utánkövetési állapottal, felelőssel és belső jegyzetekkel kerülnek a HIMATE-be.',
    'Email contact': 'E-mail küldése',
    'Contact lead updated.': 'A kapcsolati érdeklődő frissítve.',
    'System Health': 'Rendszerállapot',
    'Service Health': 'Szolgáltatásállapot',
    'Architecture': 'Architektúra',
    'Containerization': 'Konténerizáció',
    'Horizontal scaling': 'Horizontális skálázás',
    'Private services': 'Privát szolgáltatások',
    'Public ingress': 'Nyilvános belépési pont',
    'Partner databases': 'Partner-adatbázisok',
    'Persistence': 'Perzisztencia',
    'Operational Controls': 'Üzemeltetési vezérlők',
    'Provisioning': 'Provisioning',
    'Provisioning Engine': 'Provisioning motor',
    'Environments': 'Környezetek',
    'Environment': 'Környezet',
    'Connector': 'Connector',
    'Integrations': 'Integrációk',
    'Domains & Deployments': 'Domainek és telepítések',
    'Deployment': 'Telepítés',
    'Deployment status': 'Telepítési állapot',
    'Production environment': 'Éles környezet',
    'Production hostname': 'Éles hosztnév',
    'Production hostname *': 'Éles hosztnév *',
    'Verify DNS/TLS': 'DNS/TLS ellenőrzése',
    'Deploy': 'Telepítés',
    'Launch production': 'Éles indítás',
    'Go LIVE': 'Élesítés',
    'Backups & Recoverability': 'Biztonsági mentések és helyreállíthatóság',
    'Backup policy': 'Mentési szabályzat',
    'Automatic backups': 'Automatikus mentések',
    'Automatic backups enabled': 'Automatikus mentés engedélyezve',
    'Retention days': 'Megőrzési napok',
    'Max restore points': 'Maximális visszaállítási pontok',
    'Automatic backup interval (hours)': 'Automatikus mentési időköz (óra)',
    'Save policy': 'Szabályzat mentése',
    'Create restore point': 'Visszaállítási pont létrehozása',
    'Run restore test': 'Visszaállítási teszt futtatása',
    'Restore test': 'Visszaállítási teszt',
    'Restore tested': 'Visszaállítás tesztelve',
    'Offsite provider': 'Külső mentési szolgáltató',
    'Roles & Permissions': 'Szerepkörök és jogosultságok',
    'Role Matrix': 'Szerepkörmátrix',
    'Administrators': 'Adminisztrátorok',
    'Add administrator': 'Adminisztrátor hozzáadása',
    'Create administrator': 'Adminisztrátor létrehozása',
    'Edit administrator access': 'Adminisztrátori hozzáférés szerkesztése',
    'Full name': 'Teljes név',
    'Email address': 'E-mail-cím',
    'Temporary password': 'Ideiglenes jelszó',
    'New password (optional)': 'Új jelszó (opcionális)',
    'Roles': 'Szerepkörök',
    'Active account': 'Aktív fiók',
    'Effective permissions': 'Tényleges jogosultságok',
    'Administrative Event Stream': 'Adminisztratív eseménynapló',
    'Search audit history': 'Keresés az auditnaplóban',
    'All methods': 'Minden metódus',
    'All outcomes': 'Minden eredmény',
    'All resources': 'Minden erőforrás',
    'Actor': 'Végrehajtó',
    'Request ID': 'Kérésazonosító',
    'Resource': 'Erőforrás',
    'Outcome': 'Eredmény',
    'Duration': 'Időtartam',
    'HTTP status': 'HTTP-állapot',
    'Status': 'Állapot',
    'State': 'Állapot',
    'Health': 'Állapot',
    'Healthy': 'Egészséges',
    'Warning': 'Figyelmeztetés',
    'Offline': 'Offline',
    'Error': 'Hiba',
    'Success': 'Siker',
    'Active': 'Aktív',
    'Inactive': 'Inaktív',
    'Maintenance': 'Karbantartás',
    'Not licensed': 'Nincs licencelve',
    'Configure': 'Konfigurálás',
    'Apply': 'Alkalmazás',
    'Next': 'Tovább',
    'Previous': 'Vissza',
    'Refresh': 'Frissítés',
    'Close': 'Bezárás',
    'Cancel': 'Mégse',
    'Copy': 'Másolás',
    'Edit access': 'Hozzáférés szerkesztése',
    'Open URL': 'URL megnyitása',
    'Search anywhere...': 'Keresés bárhol...',
    'Search Evidence': 'Bizonyíték keresése',
    'No administrators found': 'Nem található adminisztrátor',
    'No matching audit events': 'Nincs egyező auditesemény',
    'No partner data': 'Nincs partneradat',
    'No module data': 'Nincs moduladat',
    'No impact data': 'Nincs hatásadat',
    'No reports yet': 'Még nincs jelentés',
    'No CMS pages yet': 'Még nincs CMS-oldal',
    'No CMS media yet': 'Még nincs CMS-média',
    'No service health data': 'Nincs szolgáltatásállapot-adat',
    'No environment yet': 'Még nincs környezet',
    'No connector credential yet': 'Még nincs Connector-hitelesítő adat',
    'No documents registered': 'Nincs regisztrált dokumentum',
    'No invoice records yet': 'Még nincs számlarekord',
    'You are already signed in.': 'Már be vagy jelentkezve.',
    'Continue to the HIMATE administration platform.': 'Folytatás a HIMATE adminisztrációs platformra.',
    'Open admin platform': 'Adminplatform megnyitása',
    'Workspace prepared': 'Munkaterület előkészítve',
    'Good morning,': 'Jó reggelt,',
    'Good afternoon,': 'Jó napot,',
    'Good evening,': 'Jó estét,',
    'PLATFORM OPERATIONS': 'PLATFORMÜZEMELTETÉS',
    'WEBSITE & MARKETING': 'WEBOLDAL ÉS MARKETING',
    'COMMERCIAL CONTROL': 'KERESKEDELMI VEZÉRLÉS',
    'IMPACT CONTROL': 'HATÁSVEZÉRLÉS',
    'ADMINISTRATION': 'ADMINISZTRÁCIÓ',
    'NEW PARTNER': 'ÚJ PARTNER',
    'READY': 'KÉSZ',
    'FAILED': 'SIKERTELEN',
    'QUEUED': 'SORBAN',
    'DEPLOYING': 'TELEPÍTÉS FOLYAMATBAN',
    'DEPLOYED': 'TELEPÍTVE',
    'NOT DEPLOYED': 'NINCS TELEPÍTVE',
    'UNAVAILABLE': 'NEM ELÉRHETŐ',
    'DEPRECATED': 'KIVEZETETT',
    'SUSPENDED': 'FELFÜGGESZTVE',
    'TESTING': 'TESZTELÉS',
    'LIVE': 'ÉLES',
  };




  static const Map<String, String> _extendedHu = <String, String>{
    'Culture Connects People': 'A kultúra összeköti az embereket',
    'or continue with': 'vagy folytasd ezzel',
    'Secure  •  Trusted  •  Built for a brighter tomorrow': 'Biztonságos  •  Megbízható  •  Egy fényesebb holnapra építve',
    'The brand system and responsive shell are ready. Functional implementation remains in its scheduled START cycle.': 'Az arculati rendszer és a reszponzív keret kész. A funkcionális megvalósítás az ütemezett START ciklusban folytatódik.',
    'Create a partner category first.': 'Előbb hozz létre partnerkategóriát.',
    '1 · Business identity': '1 · Üzleti identitás',
    'Add category': 'Kategória hozzáadása',
    'Unknown': 'Ismeretlen',
    'Move the partner to READY TO PROVISION before starting provisioning.': 'Állítsd a partnert READY TO PROVISION állapotba a provisioning megkezdése előtt.',
    'Store this credential now': 'Hitelesítő adat biztonságos mentése',
    'For security, HIMATE stores only the token hash. This raw credential will not be shown again.': 'Biztonsági okból a HIMATE csak a token hashét tárolja. A nyers hitelesítő adat később nem jelenik meg újra.',
    'Credential copied.': 'Hitelesítő adat másolva.',
    'I stored it securely': 'Biztonságosan elmentettem',
    'Use only for an existing/reference partner where no activation transaction applies.': 'Csak meglévő vagy referenciapartnernél használd, ahol nincs aktiválási tranzakció.',
    'Contract': 'Szerződés',
    'Invoice': 'Számla',
    'Receipt': 'Bizonylat',
    'Other': 'Egyéb',
    'All states': 'Minden állapot',
    'Generate / rotate credential': 'Hitelesítő adat létrehozása / cseréje',
    'Image': 'Kép',
    'Screenshot': 'Képernyőkép',
    'URL reference': 'URL-hivatkozás',
    'Partner declaration': 'Partnernyilatkozat',
    'Choose file': 'Fájl kiválasztása',
    'All types': 'Minden típus',
    'Integrity': 'Integritás',
    'Verify': 'Ellenőrzés',
    'Failed': 'Sikertelen',
    'Monthly': 'Havi',
    'Partner category': 'Partnerkategória',
    'Primary domain': 'Elsődleges domain',
    'Verified paid amount · USD': 'Ellenőrzött kifizetett összeg · USD',
    'Desired platform release': 'Kívánt platformkiadás',
    'Category': 'Kategória',
    'Desired release': 'Kívánt kiadás',
    'Active release': 'Aktív kiadás',
    'Staging domain': 'Staging domain',
    'Logo URL / asset reference': 'Logó URL / elemhivatkozás',
    'Internal notes': 'Belső megjegyzések',
    'Currency': 'Pénznem',
    'Initial license / activation fee': 'Kezdeti licenc / aktiválási díj',
    'Waiver reason': 'Elengedés indoka',
    'License note': 'Licenc megjegyzés',
    'Base 30-day service fee': 'Alap 30 napos szolgáltatási díj',
    'Price effective from': 'Ár érvényességének kezdete',
    'Billing contact': 'Számlázási kapcsolattartó',
    'Company address': 'Cég címe',
    'Billing phone': 'Számlázási telefonszám',
    'Display label': 'Megjelenített felirat',
    'Partner ID': 'Partnerazonosító',
    'Partner ID *': 'Partnerazonosító *',
    'HTTP(S) source URL *': 'HTTP(S) forrás URL *',
    'Partner declaration *': 'Partnernyilatkozat *',
    'Verified numeric value': 'Ellenőrzött számérték',
    'Type': 'Típus',
    'Period from': 'Időszak kezdete',
    'Period to': 'Időszak vége',
    'Method': 'Metódus',
    'e.g. Cultural Foundation': 'pl. Kulturális Alapítvány',
    'Optional RFC3339 timestamp': 'Opcionális RFC3339 időbélyeg',
    'Leave empty for global baseline': 'Hagyd üresen globális bázisértékhez',
    'Actor, request ID, resource, path or partner': 'Végrehajtó, kérésazonosító, erőforrás, útvonal vagy partner',
    'Edit commercial terms': 'Kereskedelmi feltételek szerkesztése',
    'HIMATE System': 'HIMATE System',
    'Independent services behind one authenticated public gateway.': 'Független szolgáltatások egy hitelesített nyilvános gateway mögött.',
    'Refreshing operations data': 'Üzemeltetési adatok frissítése',
    'Dashboard data is temporarily unavailable': 'Az irányítópult adatai átmenetileg nem érhetők el',
    'Add partner category': 'Partnerkategória hozzáadása',
    'New Partner · Provisioning Wizard': 'Új partner · Provisioning varázsló',
    'Partners could not be loaded': 'A partnerek nem tölthetők be',
    'Connector credential': 'Connector hitelesítő adat',
    'Generate or rotate a partner-scoped credential. The raw secret is displayed exactly once.': 'Hozz létre vagy cserélj partnerhez kötött hitelesítő adatot. A nyers titok pontosan egyszer jelenik meg.',
    'Edit legal identity, contacts, lifecycle and partner references.': 'Jogi identitás, kapcsolattartók, életciklus és partnerhivatkozások szerkesztése.',
    'Pricing & Subscription': 'Árazás és előfizetés',
    'Partner-specific license and recurring terms with an activation-date anchored 30-day service cycle.': 'Partnerspecifikus licenc- és ismétlődő feltételek, az aktiválási dátumhoz rögzített 30 napos szolgáltatási ciklussal.',
    'Register commercial document metadata with a persistent storage URL or document reference.': 'Kereskedelmi dokumentum metaadatainak rögzítése tartós tárolási URL-lel vagy dokumentumhivatkozással.',
    'Secondary data is loading independently': 'A másodlagos adatok külön töltődnek',
    'Workspace': 'Munkaterület',
    'Provisioning state, isolated partner infrastructure, staging/production and release metadata.': 'Provisioning állapot, elkülönített partner-infrastruktúra, staging/production és kiadási metaadatok.',
    'Entitlement, visibility, base-package inclusion and partner-specific pricing.': 'Jogosultság, láthatóság, alapcsomag-tagság és partnerspecifikus árazás.',
    'No impact observations yet': 'Még nincs hatásmegfigyelés',
    'Partner-scoped Connector Protocol credentials. Raw secrets are never stored by HIMATE.': 'Partnerhez kötött Connector Protocol hitelesítő adatok. A HIMATE soha nem tárol nyers titkokat.',
    'HIMATE billing profile': 'HIMATE számlázási profil',
    'Issuer and international banking data used as the foundation for future invoice-provider integration.': 'Kibocsátói és nemzetközi banki adatok a későbbi számlázási szolgáltatói integráció alapjaként.',
    'Manage catalog metadata and availability without changing the stable technical key.': 'Katalógusmetaadatok és elérhetőség kezelése a stabil technikai kulcs módosítása nélkül.',
    'Finance workspace unavailable': 'A pénzügyi munkaterület nem érhető el',
    'Manual values remain distinct from connector and verified-document provenance.': 'A kézi értékek elkülönülnek a connector- és ellenőrzött dokumentum eredetétől.',
    'Store an explicit baseline period and value for reproducible comparison.': 'Rögzíts explicit bázisidőszakot és értéket a reprodukálható összehasonlításhoz.',
    'Impact data unavailable': 'A hatásadatok nem érhetők el',
    'Partner, multi-partner and HIMATE Global PDFs generated from frozen, auditable snapshots.': 'Partner-, többpartneres és HIMATE Global PDF-ek rögzített, auditálható pillanatképekből.',
    'Stable definitions reused by manual entry, connectors and verified-document workflows.': 'Stabil definíciók, amelyeket a kézi bevitel, connectorok és ellenőrzött dokumentumfolyamatok is újrahasználnak.',
    'No cached operations data yet': 'Még nincs gyorsítótárazott üzemeltetési adat',
    'Operations data unavailable': 'Az üzemeltetési adatok nem érhetők el',
    'Readiness and liveness are monitored independently for each microservice.': 'A readiness és liveness minden mikroszolgáltatásnál külön felügyelt.',
    'Idempotent jobs can resume after interruption without creating duplicate partner infrastructure.': 'Az idempotens feladatok megszakítás után folytathatók duplikált partner-infrastruktúra létrehozása nélkül.',
    'Central audit history, administrator lifecycle, roles and backend-enforced permissions across the HIMATE control plane.': 'Központi auditnapló, adminisztrátori életciklus, szerepkörök és backend által kikényszerített jogosultságok a HIMATE vezérlősíkján.',
    'Audit history could not be loaded': 'Az auditnapló nem tölthető be',
    'HIMATE Issuer Profile': 'HIMATE kibocsátói profil',
    'No cached operations snapshot is available yet. The page is ready and data will appear automatically.': 'Még nincs elérhető gyorsítótárazott üzemeltetési pillanatkép. Az oldal kész, az adatok automatikusan megjelennek.',
    'Sign out': 'Kijelentkezés',
    'Provisioning creates the staging connector identity automatically. You can also generate or rotate it here.': 'A provisioning automatikusan létrehozza a staging connector identitását. Itt külön is létrehozhatod vagy cserélheted.',
    'Upload a PDF, image, invoice, contract, screenshot, URL or partner declaration.': 'Tölts fel PDF-et, képet, számlát, szerződést, képernyőképet, URL-t vagy partnernyilatkozatot.',
    'Mutating administration actions will appear here automatically. Adjust the filters if you are looking for earlier activity.': 'A módosító adminisztrációs műveletek automatikusan megjelennek itt. Korábbi aktivitáshoz módosítsd a szűrőket.',
    'PEOPLE  |  PROGRAMS  |  IMPACT': 'EMBEREK  |  PROGRAMOK  |  HATÁS',
    'Create & validate provisioning': 'Provisioning létrehozása és ellenőrzése',
    'Generate credential': 'Hitelesítő adat létrehozása',
    'Save commercial terms': 'Kereskedelmi feltételek mentése',
    'Base package': 'Alapcsomag',
    'Release': 'Kiadás',
    'Last error': 'Legutóbbi hiba',
    'Value': 'Érték',
    'Latest period': 'Legutóbbi időszak',
    'Observations': 'Megfigyelések',
    'Credential ID': 'Hitelesítő azonosító',
    'Rotated': 'Cserélve',
    'Last used': 'Legutóbb használva',
    'Priced defaults': 'Árazott alapértékek',
    'Annual uplift': 'Éves emelés',
    'Delta': 'Eltérés',
    'Period': 'Időszak',
    'Template': 'Sablon',
    'Snapshot': 'Pillanatkép',
    'Key': 'Kulcs',
    'Overall': 'Összesített',
    'Partner DB': 'Partner-adatbázis',
    'Storage': 'Tárolás',
    'Data sync': 'Adatszinkronizáció',
    'Last sync': 'Legutóbbi szinkron',
    'System': 'Rendszer',
    'Registration': 'Regisztráció',
    'Annual increase': 'Éves emelés',
    'Billing rule': 'Számlázási szabály',
    'Bank': 'Bank',
    'Service period': 'Szolgáltatási időszak',
    'Renewal': 'Megújítás',
    'Invoice trigger': 'Számlázási esemény',
    'Annual base-fee uplift': 'Éves alapdíj-emelés',
    'Default uplift': 'Alapértelmezett emelés',
    'External payment provider': 'Külső fizetési szolgáltató',
    'Identity boundary': 'Identitási határ',
    'Partner domain': 'Partner domain',
    'Catalog domain': 'Katalógus domain',
    'Billing domain': 'Számlázási domain',
    'Connector model': 'Connector modell',
    'Backups / restore': 'Biztonsági mentések / helyreállítás',
    'Restore': 'Helyreállítás',
    'CMS audit ·': 'CMS audit ·',
    'No media': 'Nincs média',
    'Edit CMS draft ·': 'CMS-vázlat szerkesztése ·',
    'SEO & routing': 'SEO és útvonalkezelés',
    'Published content stays available but is marked not to be indexed.': 'A publikált tartalom elérhető marad, de noindex jelölést kap.',
    'Section': 'Szekció',
    'Turning this off preserves the section content but removes it from public/preview output.': 'Kikapcsoláskor a szekció tartalma megmarad, de eltűnik a nyilvános és előnézeti kimenetből.',
    'Alt / media description': 'Alt / médialeírás',
    'HIMATE Landing': 'HIMATE nyitóoldal',
    'Describe the image or video for accessibility': 'Írd le a képet vagy videót az akadálymentességhez',
    'Preview media': 'Média előnézete',
    'Create the first immutable draft. Existing public pages remain unchanged until START-17.': 'Hozd létre az első megváltoztathatatlan vázlatot. A jelenlegi nyilvános oldalak publikálásig változatlanok maradnak.',
    'Upload CMS media': 'CMS-média feltöltése',
    'PNG, JPEG, WebP, MP4 or WebM · max 64 MiB · content-sniffed · SHA-256 verified.': 'PNG, JPEG, WebP, MP4 vagy WebM · max. 64 MiB · tartalomellenőrzött · SHA-256-tal ellenőrzött.',
    'CMS unavailable': 'A CMS nem érhető el',
    'Manage published website content, story video, media and SEO without editing source code.': 'Publikált webtartalom, story videó, média és SEO kezelése forráskód szerkesztése nélkül.',
    'Each page keeps independent draft, preview and published snapshots.': 'Minden oldal külön vázlat-, előnézeti és publikált pillanatképet tart fenn.',
    'CMS images and story videos are content-sniffed, checksum-backed and referenced by stable asset ID.': 'A CMS-képek és story videók tartalomellenőrzöttek, ellenőrzőösszeggel védettek és stabil elem-azonosítóval hivatkozottak.',
    'No sections in this draft': 'Nincsenek szekciók ebben a vázlatban',
    'Create a page draft, preview it, then publish it to activate CMS content on the public website.': 'Készíts oldalvázlatot, ellenőrizd előnézetben, majd publikáld a nyilvános weboldal aktiválásához.',
    'Upload an image or MP4/WebM story video before linking media to page sections.': 'Tölts fel képet vagy MP4/WebM story videót, mielőtt médiát kapcsolsz az oldalszekciókhoz.',
    'Add at least one visible section before publishing.': 'Publikálás előtt adj hozzá legalább egy látható szekciót.',
    'File': 'Fájl',
    'Asset ID': 'Elem-azonosító',
    'Alt text': 'Alt szöveg',
    'Suspended administrators cannot sign in or use an existing session.': 'A felfüggesztett adminisztrátorok nem jelentkezhetnek be és meglévő munkamenetet sem használhatnak.',
    'Platform Admin access required': 'Platform Admin hozzáférés szükséges',
    'Roles & Permissions could not be loaded': 'A szerepkörök és jogosultságok nem tölthetők be',
    'Backend-enforced RBAC. Read, write and approval rights are checked before each protected administration API request.': 'Backend által kikényszerített RBAC. Az olvasási, írási és jóváhagyási jogok minden védett adminisztrációs API-kérés előtt ellenőrzésre kerülnek.',
    'Roles are additive. Approval permissions protect sensitive actions such as publishing, verification and provisioning execution.': 'A szerepkörök jogosultságai összeadódnak. A jóváhagyási jogok védik az érzékeny műveleteket, például a publikálást, ellenőrzést és provisioning futtatást.',
    'Accounts are never hard-deleted from administration. Suspend access to preserve audit identity and historical attribution.': 'A fiókokat az adminisztráció soha nem törli véglegesen. Függeszd fel a hozzáférést az auditidentitás és történeti hozzárendelés megőrzéséhez.',
    'Role assignment and administrator lifecycle are protected by backend Administration permissions.': 'A szerepkör-hozzárendelést és az adminisztrátori életciklust backend Administration jogosultságok védik.',
    'Create an administrator to assign a scoped HIMATE role.': 'Hozz létre adminisztrátort egy hatókörrel rendelkező HIMATE szerepkör hozzárendeléséhez.',
    'User ID': 'Felhasználóazonosító',
    'Policy': 'Szabályzat',
    'No provisioned partner available': 'Nincs provisionált partner',
    'Start backup': 'Biztonsági mentés indítása',
    'Backup': 'Biztonsági mentés',
    'Backup completed': 'Biztonsági mentés kész',
    'Retention': 'Megőrzés',
    'Restore-point limit': 'Visszaállítási pontok korlátja',
    'Automatic interval': 'Automatikus időköz',
    'Add production': 'Production hozzáadása',
    'Staging and production release state, DNS/TLS verification and controlled READY FOR LAUNCH → LIVE transition.': 'Staging- és production kiadási állapot, DNS/TLS-ellenőrzés és vezérelt READY FOR LAUNCH → LIVE átmenet.',
    'Create production': 'Production létrehozása',
    'Runtime': 'Futtatókörnyezet',
    'Domain': 'Domain',
    'Domain checked': 'Domain ellenőrizve',
    'Launched by': 'Élesítette',
    'Launched at': 'Élesítés ideje',
    'Notification': 'Értesítés',
    'Culture Fuels Tomorrow.': 'A kultúra táplálja a holnapot.',
    '30 DAYS': '30 NAP',
    'ACTIVE': 'AKTÍV',
    'AVERAGE': 'ÁTLAG',
    'BOTH': 'MINDKETTŐ',
    'CONFIGURATION REQUIRED': 'KONFIGURÁCIÓ SZÜKSÉGES',
    'CREATING': 'LÉTREHOZÁS',
    'GLOBAL': 'GLOBÁLIS',
    'GREATER IMPACT': 'NAGYOBB HATÁS',
    'LATEST': 'LEGUTÓBBI',
    'MAINTENANCE': 'KARBANTARTÁS',
    'MODULES': 'MODULOK',
    'MORE OPPORTUNITIES': 'TÖBB LEHETŐSÉG',
    'NOT LICENSED': 'NINCS LICENCELVE',
    'OWNER': 'TULAJDONOS',
    'PARTNER': 'PARTNER',
    'STRONGER COMMUNITIES': 'ERŐSEBB KÖZÖSSÉGEK',
    'SUM': 'ÖSSZEG',
    'VERSION': 'VERZIÓ',
    'YOU': 'TE',
  };


  static const Map<String, String> _completionHu = <String, String>{
    '2 · Commercial & license evidence': '2 · Kereskedelmi és licencbizonyíték',
    '3 · System & environment': '3 · Rendszer és környezet',
    '4 · Module preset': '4 · Modulkészlet',
    'A single premium workspace for every organization connected to the HIMATE ecosystem.': 'Egyetlen prémium munkaterület a HIMATE ökoszisztémához kapcsolódó minden szervezet számára.',
    'Active modules': 'Aktív modulok',
    'Administrator / contact email *': 'Adminisztrátor / kapcsolattartó e-mail *',
    'Aggregated values follow each metric definition’s SUM, LATEST or AVERAGE rule.': 'Az összesített értékek az egyes mérőszám-definíciók SUM, LATEST vagy AVERAGE szabályát követik.',
    'Billing email': 'Számlázási e-mail',
    'Business, commercial, evidence, system identity, environment and module preset are captured before provisioning can begin.': 'A provisioning megkezdése előtt rögzítjük az üzleti, kereskedelmi, bizonyítéki, rendszeridentitási, környezeti és modul-előbeállítási adatokat.',
    'Category name': 'Kategória neve',
    'Changing the production hostname resets DNS/TLS verification and launch readiness.': 'A production hosztnév módosítása visszaállítja a DNS/TLS-ellenőrzést és az indítási készültséget.',
    'Commercial evidence requires an attached storage URL or persistent document reference.': 'A kereskedelmi bizonyítékhoz csatolt tárolási URL vagy tartós dokumentumhivatkozás szükséges.',
    'Complete the required Evidence fields.': 'Töltsd ki a kötelező bizonyítékmezőket.',
    'Connector, environment, provisioning and platform-version state aggregated per partner.': 'Partnerenként összesített connector-, környezet-, provisioning- és platformverzió-állapot.',
    'Contact email': 'Kapcsolattartói e-mail',
    'Control entitlement, partner visibility and 30-day pricing without removing the underlying module code or data.': 'A jogosultság, partnerláthatóság és 30 napos árazás kezelése az alapul szolgáló modulkód vagy adatok eltávolítása nélkül.',
    'Create a category for partner organizations that do not fit the default structure.': 'Hozz létre kategóriát azoknak a partnerszervezeteknek, amelyek nem illenek az alapértelmezett struktúrába.',
    'Create a new partner workspace': 'Új partner-munkaterület létrehozása',
    'Create a stable impact metric used consistently across partners and reporting periods.': 'Hozz létre stabil hatásmérőszámot, amely következetesen használható partnerek és jelentési időszakok között.',
    'Create a stable module key and place the new capability inside an existing HIMATE menu group.': 'Hozz létre stabil modulkulcsot, és helyezd az új képességet egy meglévő HIMATE menücsoportba.',
    'Create metric': 'Mérőszám létrehozása',
    'Create metric definitions under Impact & Reports, then record partner values manually or through the Connector Protocol.': 'Hozz létre mérőszám-definíciókat a Hatás és jelentések alatt, majd rögzíts partnerértékeket kézzel vagy a Connector Protocolon keresztül.',
    'Create production environment': 'Production környezet létrehozása',
    'Current and scheduled control areas for this partner.': 'A partner aktuális és ütemezett vezérlési területei.',
    'Current recurring': 'Aktuális ismétlődő díj',
    'Current step': 'Aktuális lépés',
    'Current total': 'Aktuális összesen',
    'Custom modules': 'Egyedi modulok',
    'Database, media and configuration are captured, encrypted and copied to the configured offsite provider.': 'Az adatbázis, a média és a konfiguráció rögzítésre, titkosításra és a beállított külső szolgáltatóhoz másolásra kerül.',
    'Defaults to partner display name': 'Alapértelmezetten a partner megjelenített neve',
    'Display name': 'Megjelenített név',
    'Display name *': 'Megjelenített név *',
    'Display name and administrator email are required.': 'A megjelenített név és az adminisztrátori e-mail megadása kötelező.',
    'Edit environment': 'Környezet szerkesztése',
    'Encrypted partner database, media and configuration restore points with offsite replication, retention and mandatory restore verification.': 'Titkosított partneradatbázis-, média- és konfigurációs visszaállítási pontok külső replikációval, megőrzéssel és kötelező helyreállítás-ellenőrzéssel.',
    'Environment configuration': 'Környezeti konfiguráció',
    'Environment status': 'Környezet állapota',
    'Every successful restore point automatically queues a real restore test from the offsite copy.': 'Minden sikeres visszaállítási pont automatikusan valódi helyreállítási tesztet állít sorba a külső másolatból.',
    'Evidence is partner-scoped, checksum-backed and explicitly verified before it can support VERIFIED_DOCUMENT provenance.': 'A bizonyíték partnerhez kötött, ellenőrzőösszeggel védett, és explicit ellenőrzés szükséges, mielőtt VERIFIED_DOCUMENT eredetet támogathat.',
    'Evidence name': 'Bizonyíték neve',
    'External report': 'Külső jelentés',
    'Extra modules': 'Extra modulok',
    'Generate a report to freeze impact metrics, data sources and Evidence references into a reproducible snapshot.': 'Készíts jelentést a hatásmérőszámok, adatforrások és bizonyítékhivatkozások reprodukálható pillanatképbe rögzítéséhez.',
    'Global and partner metrics, auditable Evidence and reproducible PDF reporting.': 'Globális és partnerszintű mérőszámok, auditálható bizonyítékok és reprodukálható PDF-jelentések.',
    'Global search will be activated in a later functional cycle.': 'A globális keresés egy későbbi funkcionális ciklusban aktiválódik.',
    'Hostname': 'Hosztnév',
    'Hostname / runtime': 'Hosztnév / futtatókörnyezet',
    'Initial environment': 'Kezdeti környezet',
    'Latest version': 'Legutóbbi verzió',
    'Leave empty for global metric': 'Hagyd üresen globális mérőszámhoz',
    'Manage hostname, platform release and deployment/environment state.': 'Hosztnév, platformkiadás és telepítési/környezeti állapot kezelése.',
    'Metrics, Evidence and reproducible reports.': 'Mérőszámok, bizonyítékok és reprodukálható jelentések.',
    'Module catalog, pricing foundations and HIMATE issuer data — governed from one place.': 'Modulkatalógus, árazási alapok és HIMATE kibocsátói adatok — egy helyről irányítva.',
    'Modules outside the base package contribute to recurring fees.': 'Az alapcsomagon kívüli modulok növelik az ismétlődő díjakat.',
    'New metric definition': 'Új mérőszám-definíció',
    'New restore point': 'Új visszaállítási pont',
    'Next cycle': 'Következő ciklus',
    'No Evidence yet': 'Még nincs bizonyíték',
    'No impact observations have been recorded yet.': 'Még nincs rögzített hatásmegfigyelés.',
    'No metric link': 'Nincs mérőszám-kapcsolat',
    'No modules match the current catalog filters.': 'Egy modul sem felel meg az aktuális katalógusszűrőknek.',
    'No partner environments': 'Nincsenek partnerkörnyezetek',
    'No partners match the current filters. Create a new partner or adjust the filters.': 'Egy partner sem felel meg az aktuális szűrőknek. Hozz létre új partnert, vagy módosítsd a szűrőket.',
    'No service-health snapshot is available yet.': 'Még nincs elérhető szolgáltatásállapot-pillanatkép.',
    'Optional — current admin is used automatically': 'Opcionális — az aktuális adminisztrátort automatikusan használjuk',
    'Optional · default title follows report type': 'Opcionális · az alapértelmezett cím a jelentéstípust követi',
    'Partner records': 'Partnerrekordok',
    'Partner-scoped impact metrics retain period, aggregation and provenance for auditable reporting.': 'A partnerhez kötött hatásmérőszámok megőrzik az időszakot, aggregációt és eredetet az auditálható jelentésekhez.',
    'Partner-scoped proof with metric/period linkage, verification state and SHA-256 integrity.': 'Partnerhez kötött bizonyíték mérőszám-/időszak-kapcsolattal, ellenőrzési állapottal és SHA-256 integritással.',
    'Permissions are additive when multiple roles are assigned.': 'Több szerepkör hozzárendelésekor a jogosultságok összeadódnak.',
    'Persistent evidence reference / URL': 'Tartós bizonyítékhivatkozás / URL',
    'Platform version': 'Platformverzió',
    'Preview created. The raw preview token is returned once and opened in a new tab.': 'Az előnézet létrejött. A nyers előnézeti token egyszer jelenik meg, és új lapon nyílik meg.',
    'Production requires an explicit public hostname. DNS and TLS must verify before launch.': 'A production környezethez explicit nyilvános hosztnév szükséges. Indítás előtt a DNS-nek és TLS-nek ellenőrzöttnek kell lennie.',
    'Provision a partner first. The backup service will then capture its isolated database, media namespace and configuration state.': 'Előbb provisionálj egy partnert. A mentési szolgáltatás ezután rögzíti az elkülönített adatbázist, média-névteret és konfigurációs állapotot.',
    'Provision a staging environment first. Production can then be configured here with an explicit public hostname.': 'Előbb provisionálj staging környezetet. Ezután itt konfigurálható a production explicit nyilvános hosztnévvel.',
    'Provisioning will create the isolated partner database, base configuration and staging environment.': 'A provisioning létrehozza az elkülönített partneradatbázist, alapkonfigurációt és staging környezetet.',
    'Provisioning, partner environments, connectors, backups and central health across the containerized HIMATE control plane.': 'Provisioning, partnerkörnyezetek, connectorok, biztonsági mentések és központi állapot a konténerizált HIMATE vezérlősíkján.',
    'Record verified metric': 'Ellenőrzött mérőszám rögzítése',
    'Record verified value': 'Ellenőrzött érték rögzítése',
    'Recorded in commercial price history': 'Rögzítve a kereskedelmi ártörténetben',
    'Recorded in module, price and subscription history': 'Rögzítve a modul-, ár- és előfizetési előzményekben',
    'Register the license invoice, receipt, contract, or payment evidence before marking the license paid.': 'A licenc kifizetettként jelölése előtt rögzítsd a licencszámlát, bizonylatot, szerződést vagy fizetési bizonyítékot.',
    'Register the production environment after staging validation and before launch.': 'A staging ellenőrzése után és az indítás előtt regisztráld a production környezetet.',
    'Report ID': 'Jelentésazonosító',
    'Required for contracts, invoices, receipts and payment evidence': 'Szerződésekhez, számlákhoz, bizonylatokhoz és fizetési bizonyítékhoz kötelező',
    'Required for traceability when status changes': 'Állapotváltozáskor a nyomon követhetőséghez kötelező',
    'Retention and scheduling are partner-scoped. Expired restore points are removed from the offsite provider.': 'A megőrzés és ütemezés partnerhez kötött. A lejárt visszaállítási pontokat eltávolítjuk a külső szolgáltatótól.',
    'Save configuration': 'Konfiguráció mentése',
    'Save environment': 'Környezet mentése',
    'Save module': 'Modul mentése',
    'Save new draft version': 'Új vázlatverzió mentése',
    'Saving creates a new immutable DRAFT version. Publishing requires a fresh PREVIEW version.': 'A mentés új, megváltoztathatatlan DRAFT verziót hoz létre. A publikáláshoz friss PREVIEW verzió szükséges.',
    'Search by actor, path, request ID, resource or partner. Filters are server-side and pagination keeps the audit page fast as history grows.': 'Keresés végrehajtó, útvonal, kérésazonosító, erőforrás vagy partner szerint. A szűrés szerveroldali, a lapozás pedig növekvő előzmények mellett is gyorsan tartja az auditoldalt.',
    'Set metric baseline': 'Mérőszám bázisértékének beállítása',
    'STAGING · required first environment': 'STAGING · kötelező első környezet',
    'System name': 'Rendszernév',
    'The backend will re-check runtime health and all launch gates before committing LIVE.': 'A backend az élesítés előtt újra ellenőrzi a futtatókörnyezet állapotát és minden indítási kaput.',
    'The durable scheduler queues a restore point when the interval is due.': 'A tartós ütemező visszaállítási pontot állít sorba az időköz esedékességekor.',
    'The report freezes metrics, sources and Evidence references into a reproducible snapshot before PDF rendering.': 'A jelentés a PDF-renderelés előtt reprodukálható pillanatképbe rögzíti a mérőszámokat, forrásokat és bizonyítékhivatkozásokat.',
    'The verified reference catalog stays centrally governed while custom modules can be added without changing the partner data model.': 'Az ellenőrzött referenciakatalógus központilag irányított marad, miközben egyedi modulok adhatók hozzá a partner adatmodell módosítása nélkül.',
    'The workspace is ready. The latest background health snapshot will appear automatically when available.': 'A munkaterület kész. A legfrissebb háttér-állapotpillanatkép automatikusan megjelenik, amint elérhető.',
    'This changes the environment from READY FOR LAUNCH to LIVE and records the launch actor.': 'Ez READY FOR LAUNCH állapotból LIVE állapotba viszi a környezetet, és rögzíti az élesítést végző személyt.',
    'This observation will use VERIFIED_DOCUMENT provenance and is cryptographically tied to the selected Evidence record.': 'Ez a megfigyelés VERIFIED_DOCUMENT eredetet használ, és kriptográfiailag a kiválasztott bizonyítékrekordhoz kötött.',
    'Title, file, partner, metric, URL…': 'Cím, fájl, partner, mérőszám, URL…',
    'Verified metric': 'Ellenőrzött mérőszám',
    'Versioned marketing content and publishing workflow.': 'Verziózott marketingtartalom és publikálási munkafolyamat.',
  };


  static const Map<String, String> _seoHu = <String, String>{
    'SEO & Keywords': 'SEO és kulcsszavak',
    'Global bilingual keywords, structured SEO defaults and automatic page-content analysis.': 'Globális kétnyelvű kulcsszavak, strukturált SEO-alapértékek és automatikus oldaltartalom-elemzés.',
    'SEO settings unavailable': 'A SEO-beállítások nem érhetők el',
    'Bilingual keywords': 'Kétnyelvű kulcsszavak',
    'English + Hungarian': 'Angol + magyar',
    'Automatic audit': 'Automatikus audit',
    'Title, meta, content and keyword fit': 'Cím, metaadat, tartalom és kulcsszó-illeszkedés',
    'Structured data': 'Strukturált adatok',
    'Published EN/HU alternates': 'Publikált EN/HU alternatívák',
    'Global keywords · English': 'Globális kulcsszavak · angol',
    'Global keywords · Hungarian': 'Globális kulcsszavak · magyar',
    'Comma-separated · up to 30 unique keywords': 'Vesszővel elválasztva · legfeljebb 30 egyedi kulcsszó',
    'Schema.org organization name': 'Schema.org szervezet neve',
    'Schema.org organization HTTPS URL': 'Schema.org szervezet HTTPS URL-je',
    'Default Open Graph image': 'Alapértelmezett Open Graph kép',
    'No global default image': 'Nincs globális alapértelmezett kép',
    'SEO settings have not been published yet': 'A SEO-beállítások még nincsenek publikálva',
    'Save SEO draft': 'SEO-vázlat mentése',
    'Publish SEO settings': 'SEO-beállítások publikálása',
    'SEO settings draft saved.': 'A SEO-beállítások vázlata elmentve.',
    'SEO settings published to the public website.': 'A SEO-beállítások publikálva a nyilvános weboldalon.',
    'Automatic SEO Audit': 'Automatikus SEO-audit',
    'Draft-aware analysis of every CMS page using its language-specific content and keywords.': 'Minden CMS-oldal vázlattudatos elemzése a nyelvspecifikus tartalom és kulcsszavak alapján.',
    'Refresh audit': 'Audit frissítése',
    'No pages available for SEO audit': 'Nincs SEO-auditra elérhető oldal',
    'Create a CMS page draft to begin automatic SEO analysis.': 'Hozz létre CMS-oldalvázlatot az automatikus SEO-elemzés megkezdéséhez.',
    'Suggested keywords': 'Javasolt kulcsszavak',
    'Name': 'Név',
    'Email': 'E-mail',
    'Organization': 'Szervezet',
    'Metric': 'Mérőszám',
    'Report': 'Jelentés',
    'Version': 'Verzió',
    'arts, culture, communities': 'művészet, kultúra, közösségek',
    'SEO title length': 'SEO-cím hossza',
    'Meta description length': 'Meta leírás hossza',
    'Visible content characters': 'Látható tartalom karakterszáma',
    'Page keywords': 'Oldalszintű kulcsszavak',
    'Comma-separated · up to 24 unique page keywords': 'Vesszővel elválasztva · legfeljebb 24 egyedi oldalszintű kulcsszó',
    'SEO title is missing.': 'Hiányzik a SEO-cím.',
    'SEO title is shorter than 30 characters.': 'A SEO-cím 30 karakternél rövidebb.',
    'SEO title is longer than 60 characters.': 'A SEO-cím 60 karakternél hosszabb.',
    'Meta description is missing.': 'Hiányzik a meta leírás.',
    'Meta description is shorter than 120 characters.': 'A meta leírás 120 karakternél rövidebb.',
    'Meta description is longer than 160 characters.': 'A meta leírás 160 karakternél hosszabb.',
    'Canonical URL must be an absolute HTTPS URL.': 'A kanonikus URL-nek teljes HTTPS URL-nek kell lennie.',
    'Add at least three page-specific keywords.': 'Adj meg legalább három oldalspecifikus kulcsszót.',
    'Consider focusing page-specific keywords to twelve or fewer.': 'Érdemes az oldalspecifikus kulcsszavakat legfeljebb tizenkettőre fókuszálni.',
    'Global keywords for this language are sparse.': 'Kevés globális kulcsszó van beállítva ehhez a nyelvhez.',
    'Visible page content is thin for organic search.': 'A látható oldaltartalom kevés az organikus kereséshez.',
    'Page keywords are not represented in visible page content.': 'Az oldalspecifikus kulcsszavak nem jelennek meg a látható oldaltartalomban.',
    'Open Graph title will fall back to the SEO title.': 'Az Open Graph cím a SEO-címre fog visszaesni.',
    'Open Graph description will fall back to the meta description.': 'Az Open Graph leírás a meta leírásra fog visszaesni.',
    'NEEDS ATTENTION': 'FIGYELMET IGÉNYEL',
    'BLOCKED': 'BLOKKOLVA',
  };


  static const Map<String, String> _start22Hu = <String, String>{
    'Klavierhaus Data Connector': 'Klavierhaus adatkapcsolat',
    'One-way, allowlisted Klavierhaus → HIMATE data contract with signed batches, reconciliation and seven-year retention.': 'Egyirányú, engedélyezési listás Klavierhaus → HIMATE adatkapcsolat aláírt batch-ekkel, egyeztetéssel és hét éves megőrzéssel.',
    'Refresh connector': 'Adatkapcsolat frissítése',
    'Klavierhaus connector unavailable': 'A Klavierhaus adatkapcsolat nem érhető el',
    'Data direction': 'Adatirány',
    'Klavierhaus → HIMATE': 'Klavierhaus → HIMATE',
    'Security': 'Biztonság',
    'HMAC-SHA-512 + replay protection': 'HMAC-SHA-512 + visszajátszás elleni védelem',
    'HMAC-SHA-512 + AES-256-GCM': 'HMAC-SHA-512 + AES-256-GCM',
    'Data at rest': 'Tárolt adatok védelme',
    'Encryption key version': 'Titkosítási kulcs verziója',
    'AES-256-GCM envelope encrypted': 'AES-256-GCM envelope titkosított',
    'Data contract': 'Adatszerződés',
    '38 allowlisted modules': '38 engedélyezett modul',
    'Retention': 'Megőrzés',
    'HIMATE 7 years': 'HIMATE 7 év',
    'Connection & Sync': 'Kapcsolat és szinkron',
    'Partner': 'Partner',
    'Environment': 'Környezet',
    'Health': 'Állapot',
    'Sync status': 'Szinkron állapota',
    'Protocol version': 'Protokollverzió',
    'Klavierhaus version': 'Klavierhaus verzió',
    'Last heartbeat': 'Legutóbbi heartbeat',
    'Last data sync': 'Legutóbbi adatszinkron',
    'Last reconciliation': 'Legutóbbi egyeztetés',
    'Retention & Protection': 'Megőrzés és védelem',
    'Retention policy': 'Megőrzési szabály',
    'Retention period': 'Megőrzési idő',
    'Oldest retained record': 'Legrégebbi megőrzött rekord',
    'Next retention expiry': 'Következő megőrzési lejárat',
    'Legal holds': 'Jogi megőrzési zárolások',
    'Privacy delete requests': 'Adatvédelmi törlési kérelmek',
    'Secrets in exported datasets': 'Titkok az exportált adatokban',
    'Raw customer message bodies': 'Nyers ügyfélüzenet-tartalom',
    'Prohibited': 'Tiltott',
    'RECEIVED': 'FOGADVA',
    'SYNCED': 'SZINKRONBAN',
    'STALE': 'ELAVULT',
    'OUT_OF_SYNC': 'ELTÉRÉS',
    'NEVER': 'MÉG SOHA',
  };

  static const Map<String, String> _designHu = <String, String>{
    'Design Guide': 'Arculati útmutató',
    'Global website brand controls for logo, colors, typography, buttons and bilingual navigation.': 'Globális weboldal-arculati beállítások logóhoz, színekhez, tipográfiához, gombokhoz és kétnyelvű navigációhoz.',
    'Brand': 'Arculat',
    'Published globally': 'Globálisan publikálva',
    'Languages': 'Nyelvek',
    'English + Hungarian labels': 'Angol + magyar feliratok',
    'Preview-safe': 'Előnézet-biztos',
    'Draft before publish': 'Vázlat publikálás előtt',
    'Every save/publish recorded': 'Minden mentés és publikálás naplózva',
    'Website logo': 'Weboldal logója',
    'Default HIMATE logo': 'Alapértelmezett HIMATE logó',
    'Primary navy': 'Elsődleges sötétkék',
    'Brand gold': 'Arculati arany',
    'Page background': 'Oldal háttere',
    'Body text color': 'Törzsszöveg színe',
    'Heading font': 'Címsor betűtípusa',
    'Body font': 'Törzsszöveg betűtípusa',
    'Button corner radius': 'Gombsarkok lekerekítése',
    '0–40 pixels': '0–40 képpont',
    'HIMATE website preview': 'HIMATE weboldal előnézet',
    'The published Design Guide is applied without editing source code.': 'A publikált Arculati útmutató forráskód szerkesztése nélkül lép életbe.',
    'Primary action': 'Elsődleges művelet',
    'Website Navigation': 'Weboldal navigáció',
    'Control visible public menu items, bilingual labels and order.': 'A nyilvános menüpontok láthatóságának, kétnyelvű feliratainak és sorrendjének kezelése.',
    'Add navigation item': 'Navigációs elem hozzáadása',
    'No navigation items': 'Nincsenek navigációs elemek',
    'Add at least one item for public navigation.': 'Adj hozzá legalább egy elemet a nyilvános navigációhoz.',
    'Navigation item': 'Navigációs elem',
    'Remove': 'Eltávolítás',
    'English label': 'Angol felirat',
    'Hungarian label': 'Magyar felirat',
    'URL': 'URL',
    'Visible in navigation': 'Látható a navigációban',
    'No Design Guide publication yet': 'Az Arculati útmutató még nincs publikálva',
    'Save design draft': 'Arculati vázlat mentése',
    'Publish design': 'Arculat publikálása',
    'Design draft saved.': 'Az arculati vázlat elmentve.',
    'Design Guide published to the public website.': 'Az Arculati útmutató publikálva a nyilvános weboldalon.',
    'Design settings loaded from defaults': 'Az arculati beállítások alapértékekből betöltve',
    'Use six-digit hexadecimal colors, for example #06172C.': 'Használj hatjegyű hexadecimális színeket, például #06172C.',
    'Button radius must be between 0 and 40.': 'A gombsarkok lekerekítése 0 és 40 között lehet.',
    'Navigation supports at most 12 items.': 'A navigáció legfeljebb 12 elemet támogat.',
    'Every navigation item requires English and Hungarian labels.': 'Minden navigációs elemhez angol és magyar felirat szükséges.',
    'Navigation URLs must be internal paths or absolute HTTP(S) URLs.': 'A navigációs URL-ek belső útvonalak vagy teljes HTTP(S) URL-ek lehetnek.',
    'Navigation order values must be unique.': 'A navigáció sorrendértékeinek egyedinek kell lenniük.',
    'Language': 'Nyelv',
    'English (US)': 'Angol (USA)',
    'Magyar': 'Magyar',
    'Stable page key *': 'Stabil oldalkulcs *',
    'Page key, name and slug are required.': 'Az oldalkulcs, a név és a slug megadása kötelező.',
    'Versions': 'Verziók',
    'Preview token': 'Előnézeti token',
    'Not issued': 'Nincs kiadva',
    'Page key': 'Oldalkulcs',
  };

  static const Map<String, String> _start23Hu = <String, String>{
    'Active role': 'Aktív szerepkör',
    'Commercial control': 'Kereskedelmi kontroll',
    'Company / billing email': 'Cég / számlázási e-mail',
    'Create role': 'Szerepkör létrehozása',
    'Custom roles': 'Egyedi szerepkörök',
    'Deactivate only after the role is removed from all administrators.': 'Csak akkor deaktiváld, ha a szerepkört minden adminisztrátortól eltávolítottad.',
    'Edit company': 'Cégadatok szerkesztése',
    'Edit role': 'Szerepkör szerkesztése',
    'Finance': 'Pénzügy',
    'Full control': 'Teljes hozzáférés',
    'HIMATE company settings updated.': 'A HIMATE cégbeállításai frissítve.',
    'Legal company name': 'Hivatalos cégnév',
    'Operations': 'Üzemeltetés',
    'Permission matrix': 'Jogosultsági mátrix',
    'Platform': 'Platform',
    'Read, write and approval permissions are enforced by the backend. administration.approve and System Owner authority cannot be delegated through a custom role.': 'Az olvasási, írási és jóváhagyási jogosultságokat a backend kényszeríti ki. Az administration.approve és a Rendszertulajdonos jogosultsága nem delegálható egyedi szerepkörrel.',
    'Registered address': 'Bejegyzett cím',
    'Role name *': 'Szerepkör neve *',
    'Stable role key *': 'Stabil szerepkörkulcs *',
    'Tax / VAT ID': 'Adó / ÁFA-azonosító',
    'Technical operations': 'Technikai üzemeltetés',
    'Every successful restore point automatically queues a real restore test from the durable stored copy.': 'Minden sikeres visszaállítási pont automatikusan valódi visszaállítási tesztet indít a tartósan tárolt példányból.',
    'Backup storage': 'Biztonsági mentés tárhelye',
    'Encrypted partner database, media and configuration restore points with durable storage, retention and mandatory restore verification.': 'Titkosított partner-adatbázis-, média- és konfigurációs visszaállítási pontok tartós tárolással, megőrzéssel és kötelező visszaállítás-ellenőrzéssel.',
    'Retention and scheduling are partner-scoped. Expired restore points are removed from durable backup storage.': 'A megőrzés és az ütemezés partnerhez kötött. A lejárt visszaállítási pontokat eltávolítjuk a tartós biztonsági mentés tárhelyéről.',
    'DRAFT → PREVIEW → PUBLISHED': 'VÁZLAT → ELŐNÉZET → PUBLIKÁLT',
    'Every edit creates a new version': 'Minden szerkesztés új verziót hoz létre',
    'Public boundary': 'Nyilvános határ',
    'Published content only': 'Csak publikált tartalom',
    'Published history remains restorable': 'A publikált előzmények visszaállíthatók maradnak',
    'Rollback': 'Visszaállítás',
    'Versioning': 'Verziókezelés',
    'Workflow': 'Munkafolyamat',
    'AGREED required for new partners': 'Új partnereknél AGREED állapot szükséges',
    'Adapter type': 'Adapter típusa',
    'Aggregated/minimized data only': 'Csak aggregált/minimalizált adatok',
    'Agreed': 'Elfogadva',
    'Agreement': 'Megállapodás',
    'Agreement note': 'Megállapodási megjegyzés',
    'Agreement reference': 'Megállapodási hivatkozás',
    'Agreement status': 'Megállapodás állapota',
    'Agreement transition is recorded as a billing event': 'A megállapodás állapotváltása számlázási eseményként kerül rögzítésre',
    'Allowed domains': 'Engedélyezett domainek',
    'An AGREED commercial agreement requires a persistent agreement reference.': 'Az AGREED kereskedelmi megállapodáshoz tartós megállapodási hivatkozás szükséges.',
    'Commercial agreement updated.': 'A kereskedelmi megállapodás frissítve.',
    'Commercial state changes will appear here as immutable billing events.': 'A kereskedelmi állapot változásai itt megváltoztathatatlan számlázási eseményekként jelennek meg.',
    'Commercial-state access fails closed when disabled.': 'A kereskedelmi állapot elérése letiltáskor biztonságosan zár.',
    'Connector credential binds the partner identity': 'A Connector hitelesítőadata a partnerazonossághoz kötött',
    'Credential-bound tenant isolation': 'Hitelesítőadathoz kötött tenant-izoláció',
    'Custom API adapter': 'Egyedi API-adapter',
    'Domain binding': 'Domain-hozzárendelés',
    'Enabled': 'Engedélyezve',
    'Entitlements + aggregated results': 'Jogosultságok + aggregált eredmények',
    'Existing site stays intact': 'A meglévő weboldal változatlan marad',
    'Generic HTTP / REST': 'Általános HTTP / REST',
    'Partner Website Adapter': 'Partner weboldal-adapter',
    'Partner Website Adapter updated.': 'A partner weboldal-adapter frissítve.',
    'Partner website base URL': 'Partner weboldal alap-URL-je',
    'Primary partner domain must be allowed': 'Az elsődleges partnerdomaint engedélyezni kell',
    'Privacy': 'Adatvédelem',
    'Provisioning gate': 'Provisioning kapu',
    'Signed contract / persistent document reference': 'Aláírt szerződés / tartós dokumentumhivatkozás',
    'Tenant scope': 'Tenant-hatókör',
    'Website base URL and at least one allowed domain are required.': 'A weboldal alap-URL-je és legalább egy engedélyezett domain szükséges.',
    'WordPress adapter': 'WordPress-adapter',
    '30 days from activation date': '30 nap az aktiválás dátumától',
    'Activation invoice': 'Aktiválási számla',
    'Activation-fee invoice reference *': 'Aktiválási díj számlahivatkozása *',
    'Active portal access': 'Aktív portál-hozzáférés',
    'Admin': 'Adminisztrátor',
    'Agreement + PAID license + evidence are required': 'Megállapodás + PAID licenc + bizonyíték szükséges',
    'Asynchronous queue': 'Aszinkron várólista',
    'Billing': 'Számlázás',
    'Capture': 'Rögzítés',
    'Commercial agreement reference *': 'Kereskedelmi megállapodás hivatkozása *',
    'Content-sniffed · max 20 MiB · SHA-256': 'Tartalomellenőrzött · max. 20 MiB · SHA-256',
    'Display name, administrator email, commercial agreement and activation invoice reference are required.': 'A megjelenítési név, az adminisztrátori e-mail, a kereskedelmi megállapodás és az aktiválási számla hivatkozása kötelező.',
    'Edit portal user': 'Portálfelhasználó szerkesztése',
    'Every 30 days': '30 naponta',
    'Explicit commercial agreement is required': 'Kifejezett kereskedelmi megállapodás szükséges',
    'Frozen before PDF generation': 'PDF-generálás előtt rögzítve',
    'January 1': 'Január 1.',
    'Mutating admin API calls': 'Módosító admin API-hívások',
    'Owner': 'Tulajdonos',
    'Partner Portal role': 'Partner Portal szerepkör',
    'Payment evidence name': 'Fizetési bizonyíték neve',
    'Payment evidence reference / URL': 'Fizetési bizonyíték hivatkozása / URL-je',
    'Persistent invoice URL / document reference': 'Tartós számla-URL / dokumentumhivatkozás',
    'Persistent invoice reference is recorded': 'A tartós számlahivatkozás rögzítésre kerül',
    'Register payment evidence or a receipt before marking the activation license paid.': 'Az aktiválási licenc kifizetettként jelölése előtt rögzíts fizetési bizonyítékot vagy bizonylatot.',
    'Reproducible': 'Reprodukálható',
    'Service cycle': 'Szolgáltatási ciklus',
    'Signed contract / agreement reference': 'Aláírt szerződés / megállapodási hivatkozás',
    'URL evidence is referenced, never fetched': 'Az URL-bizonyíték csak hivatkozásként szerepel, a rendszer nem tölti le',
    'URL safety': 'URL-biztonság',
    'Validation': 'Ellenőrzés',
    'Viewer': 'Megtekintő',
    'Write path': 'Írási útvonal',
    'Add group': 'Csoport hozzáadása',
    'Add relation': 'Kapcsolat hozzáadása',
    'Artifact reference / image digest': 'Artifact-hivatkozás / image digest',
    'Artifact type': 'Artifact típusa',
    'Branch / tag': 'Branch / tag',
    'Commit SHA': 'Commit SHA',
    'Edit': 'Szerkesztés',
    'Edit metrics': 'Mérőszámok szerkesztése',
    'Git repository': 'Git repository',
    'Group': 'Csoport',
    'Group name *': 'Csoport neve *',
    'Manage': 'Kezelés',
    'Metric keys': 'Mérőszámkulcsok',
    'Minimum platform version': 'Minimális platformverzió',
    'Module group': 'Modulcsoport',
    'Module type': 'Modultípus',
    'Owner / team': 'Tulajdonos / csapat',
    'Relationship': 'Kapcsolat',
    'Relationship note': 'Kapcsolati megjegyzés',
    'Search modules, source or owner...': 'Keresés modul, forrás vagy tulajdonos szerint...',
    'Sort order': 'Rendezési sorrend',
    'Source path': 'Forrásútvonal',
    'Stable group key *': 'Stabil csoportkulcs *',
    'Stable module key *': 'Stabil modulkulcs *',
    'Target module': 'Célmodul',
    'Control-plane events that match your permissions.': 'A jogosultságaidnak megfelelő control-plane események.',
    'Mark all read': 'Összes megjelölése olvasottként',
    'Notifications': 'Értesítések',
    'Unread only': 'Csak olvasatlan',
    'Access is restricted to your organization. Tenant scope is enforced by HIMATE.': 'A hozzáférés a saját szervezetedre korlátozott. A tenant-hatókört a HIMATE kényszeríti ki.',
    'Activate module': 'Modul aktiválása',
    'Add user': 'Felhasználó hozzáadása',
    'Back': 'Vissza',
    'Continue renewal': 'Megújítás folytatása',
    'Edit profile': 'Profil szerkesztése',
    'Logo URL': 'Logó URL',
    'Partner Portal': 'Partnerportál',
    'Password': 'Jelszó',
    'Portal role': 'Portálszerepkör',
    'Remember me': 'Maradjak bejelentkezve',
    'Your modules, results, billing and company workspace.': 'A moduljaid, eredményeid, számlázásod és vállalati munkaterületed.',
    'Schema.org WebPage JSON-LD': 'Schema.org WebPage JSON-LD',
    'hreflang': 'hreflang',
    'Responsive & Functional QA': 'Reszponzív és funkcionális QA',
    'Phone': 'Telefon',
    'Tablet': 'Tablet',
    'Laptop': 'Laptop',
    'Desktop': 'Asztali gép',
    'Long-data safe': 'Hosszú adatokra felkészítve',
    'Touch safe': 'Érintésre optimalizálva',
    'Encrypted · restore verified': 'Titkosított · visszaállítás ellenőrizve',
    'Partner × Module Commercial Matrix': 'Partner × Modul kereskedelmi mátrix',
    'Search partner or module...': 'Keresés partner vagy modul szerint...',
    'All partners': 'Minden partner',
    'All modules': 'Minden modul',
    'Partner': 'Partner',
    'Module': 'Modul',
    'Default 30-day price': 'Alapértelmezett 30 napos díj',
    'Default activation fee': 'Alapértelmezett aktiválási díj',
    'Partner 30-day price': 'Partner 30 napos díja',
    'Partner activation fee': 'Partner aktiválási díja',
    'Activation fee effective at': 'Aktiválási díj érvényességének kezdete',
    'Edit commercial pricing': 'Kereskedelmi árazás szerkesztése',
    'Save commercial terms': 'Kereskedelmi feltételek mentése',
    'Current period price': 'Aktuális periódus díja',
    'Configured 30-day price': 'Beállított 30 napos díj',
    'Next configured price': 'Következő beállított díj',
    'Activation fee': 'Aktiválási díj',
    'Current period': 'Aktuális periódus',
    'Renewal': 'Megújítás',
    'Partner visibility': 'Partneroldali láthatóság',
    'Visible': 'Látható',
    'Hidden': 'Rejtett',
    'Included in base service': 'Az alapszolgáltatás része',
    'Visible to partner': 'Látható a partner számára',
    'Auto-renew': 'Automatikus megújítás',
    'Cancels at period end': 'Megszűnik a periódus végén',
    'No renewal': 'Nincs megújítás',
    'No subscription': 'Nincs előfizetés',
    'Not started': 'Még nem indult el',
    'Commercial prices must be zero or greater.': 'A kereskedelmi díjak nem lehetnek negatívak.',
    'Partner-module commercial terms updated.': 'A partner–modul kereskedelmi feltételei frissültek.',
    'No partner-module assignments found': 'Nem található partner–modul hozzárendelés',
    'Edit commercial terms': 'Kereskedelmi feltételek szerkesztése',
    '30-day price': '30 napos díj',
    'View by partner': 'Nézet partner szerint',
    'View by module': 'Nézet modul szerint',
    'Commercial history': 'Kereskedelmi előzmények',
    'Previous value': 'Korábbi érték',
    'New value': 'Új érték',
    'Effective at': 'Érvényes ettől',
    'Actor': 'Módosító',
    'Reason': 'Indok',
    'No commercial history yet': 'Még nincs kereskedelmi előzmény',
    'The first partner-specific change will appear here.': 'Az első partner-specifikus módosítás itt jelenik meg.',
    'Commercial and entitlement changes are retained with actor, effective time and reason.': 'A kereskedelmi és jogosultsági változások módosítóval, érvényességi idővel és indokkal együtt megőrzésre kerülnek.',
    'Activation date': 'Aktiválás dátuma',
    'Next billing date': 'Következő számlázás dátuma',
    'Next billing price': 'Következő számlázási díj',
    'Price source': 'Ár forrása',
    'Activation fee source': 'Aktiválási díj forrása',
    'Partner History': 'Partner előzmény',
    'Partner Override': 'Partner-specifikus felülírás',
    'Module Default': 'Modul alapérték',
    'Partner-specific commercial pricing. Current paid-period snapshots remain immutable.': 'Partner-specifikus kereskedelmi árazás. Az aktuális fizetett periódus pillanatképe változatlan marad.',
    'Included modules remain visible in the commercial matrix but add no recurring module fee.': 'Az alapszolgáltatásba foglalt modulok láthatók maradnak a kereskedelmi mátrixban, de nem növelik az ismétlődő moduldíjat.',
    'Close': 'Bezárás',
  };


  static String literal(String locale, String value) {
    if (locale != 'hu_HU' || value.trim().isEmpty) return value;
    final exact = _literalHu[value] ?? _extendedHu[value] ?? _completionHu[value] ?? _seoHu[value] ?? _start22Hu[value] ?? _designHu[value] ?? _start23Hu[value];
    if (exact != null) return exact;

    String countLabel(String suffix, String translatedSuffix) {
      if (!value.endsWith(suffix)) return '';
      final raw = value.substring(0, value.length - suffix.length).trim();
      return int.tryParse(raw) == null ? '' : '$raw $translatedSuffix';
    }

    for (final pair in <List<String>>[
      [' partners', 'partner'],
      [' roles', 'szerepkör'],
      [' services', 'szolgáltatás'],
      [' reports', 'jelentés'],
      [' metrics', 'mérőszám'],
      [' leads', 'érdeklődő'],
      [' records', 'rekord'],
      [' batches', 'batch'],
      [' route errors', 'útválasztási hiba'],
      [' shown', 'megjelenítve'],
    ]) {
      final translated = countLabel(pair[0], pair[1]);
      if (translated.isNotEmpty) return translated;
    }

    if (value.startsWith('CMS audit · ')) {
      return 'CMS-audit · ${value.substring('CMS audit · '.length)}';
    }
    if (value.startsWith('Edit CMS draft · ')) {
      return 'CMS-vázlat szerkesztése · ${value.substring('Edit CMS draft · '.length)}';
    }
    if (value.startsWith('Version history · ')) {
      return 'Verzióelőzmények · ${value.substring('Version history · '.length)}';
    }
    if (value.startsWith('Section ')) {
      return 'Szekció ${value.substring('Section '.length)}';
    }
    if (value.startsWith('Version ')) {
      return 'Verzió ${value.substring('Version '.length)}';
    }
    if (value.startsWith('Agreement could not be updated: ')) {
      return 'A megállapodás nem frissíthető: ${value.substring('Agreement could not be updated: '.length)}';
    }
    if (value.startsWith('Website adapter could not be updated: ')) {
      return 'A weboldal-adapter nem frissíthető: ${value.substring('Website adapter could not be updated: '.length)}';
    }
    if (value.startsWith('New Partner wizard failed: ')) {
      return 'Az új partner varázsló sikertelen: ${value.substring('New Partner wizard failed: '.length)}';
    }
    if (value.startsWith('Provisioning could not complete: ')) {
      return 'A provisioning nem fejeződött be: ${value.substring('Provisioning could not complete: '.length)}';
    }
    if (value.startsWith('Credential operation failed: ')) {
      return 'A hitelesítőadat-művelet sikertelen: ${value.substring('Credential operation failed: '.length)}';
    }
    if (value.startsWith('Launch blockers: ')) {
      return 'Indítási blokkolók: ${value.substring('Launch blockers: '.length)}';
    }
    if (value.startsWith('PARTNER WORKSPACE  |  ')) {
      return 'PARTNER MUNKATERÜLET  |  ${value.substring('PARTNER WORKSPACE  |  '.length)}';
    }
    for (final pair in <List<String>>[
      [' definitions', 'definíció'],
      [' jobs', 'feladat'],
      [' admins', 'adminisztrátor'],
      [' matched', 'találat'],
      [' RECORDS', 'REKORD'],
    ]) {
      final translated = countLabel(pair[0], pair[1]);
      if (translated.isNotEmpty) return translated;
    }
    if (value.startsWith('Environment: ') && value.contains(' · Version: ')) {
      final parts = value.substring('Environment: '.length).split(' · Version: ');
      if (parts.length == 2) return 'Környezet: ${parts[0]} · Verzió: ${parts[1]}';
    }
    if (value.startsWith('Evidence integrity check failed: ')) {
      return 'A bizonyíték integritás-ellenőrzése sikertelen: ${value.substring('Evidence integrity check failed: '.length)}';
    }
    if (value.startsWith('Evidence integrity: ')) {
      return 'Bizonyíték integritása: ${value.substring('Evidence integrity: '.length)}';
    }
    if (value.startsWith('Showing ') && value.contains(' of ')) {
      final body = value.substring('Showing '.length).split(' of ');
      if (body.length == 2) return '${body[0]} / ${body[1]} megjelenítve';
    }
    if (value.startsWith('Assigned: ')) {
      return 'Felelős: ${value.substring('Assigned: '.length)}';
    }
    if (value.startsWith('Navigation item ')) {
      return 'Navigációs elem ${value.substring('Navigation item '.length)}';
    }
    if (value.startsWith('SEO published ')) {
      return 'SEO publikálva: ${value.substring('SEO published '.length)}';
    }
    if (value.startsWith('Average ') && value.endsWith('/100')) {
      return 'Átlag: ${value.substring('Average '.length)}';
    }
    if (value.endsWith(' ready')) {
      final raw = value.substring(0, value.length - ' ready'.length).trim();
      if (int.tryParse(raw) != null) return '$raw kész';
    }
    if (value.endsWith(' need attention')) {
      final raw = value.substring(0, value.length - ' need attention'.length).trim();
      if (int.tryParse(raw) != null) return '$raw figyelmet igényel';
    }
    if (value.endsWith(' years')) {
      final raw = value.substring(0, value.length - ' years'.length).trim();
      if (int.tryParse(raw) != null) return '$raw év';
    }
    if (value.contains(' / ') && value.endsWith(' modules')) {
      final raw = value.substring(0, value.length - ' modules'.length);
      return '$raw modul';
    }
    if (value.startsWith('Published ')) {
      return 'Publikálva: ${value.substring('Published '.length)}';
    }
    if (value.startsWith('Page ') && value.contains(' of ')) {
      final body = value.substring(5).split(' of ');
      if (body.length == 2) return '${body[0]} / ${body[1]} oldal';
    }

    return value;
  }

  static String text(String locale, String key) {
    final normalized = locale == 'hu_HU' ? 'hu_HU' : 'en_US';
    return _values[normalized]?[key] ?? _values['en_US']?[key] ?? key;
  }

  static String dateTime(String locale, DateTime value) {
    final tag = locale == 'hu_HU' ? 'hu_HU' : 'en_US';
    return intl.DateFormat.yMMMd(tag).add_Hm().format(value.toLocal());
  }

  static String currency(String locale, num value, {String currency = 'USD'}) {
    final tag = locale == 'hu_HU' ? 'hu_HU' : 'en_US';
    return intl.NumberFormat.simpleCurrency(locale: tag, name: currency).format(value);
  }
}

bool himatePasswordMeetsPolicy(String value) {
  if (value.runes.length < 12) return false;
  return RegExp(r'[a-z]').hasMatch(value) &&
      RegExp(r'[A-Z]').hasMatch(value) &&
      RegExp(r'[0-9]').hasMatch(value) &&
      RegExp(r'[^A-Za-z0-9\s]').hasMatch(value);
}

String? himatePasswordPolicyMessage(String locale, String value) =>
    himatePasswordMeetsPolicy(value) ? null : HimateI18n.text(locale, 'passwordPolicy');
