part of 'main.dart';

const himateSupportedLocales = <Locale>[
  Locale('en', 'US'),
  Locale('hu', 'HU'),
];

Locale himateLocaleFromCode(String? code) {
  switch ((code ?? '').trim()) {
    case 'hu_HU':
      return const Locale('hu', 'HU');
    default:
      return const Locale('en', 'US');
  }
}

String himateLocaleCode(Locale locale) =>
    locale.languageCode.toLowerCase() == 'hu' ? 'hu_HU' : 'en_US';

String tr(BuildContext context, String key) =>
    HimateI18n.text(himateLocaleCode(Localizations.localeOf(context)), key);


class LText extends StatelessWidget {
  const LText(
    this.data, {
    super.key,
    this.style,
    this.strutStyle,
    this.textAlign,
    this.textDirection,
    this.locale,
    this.softWrap,
    this.overflow,
    this.textScaler,
    this.maxLines,
    this.semanticsLabel,
    this.textWidthBasis,
    this.textHeightBehavior,
    this.selectionColor,
  });

  final String data;
  final TextStyle? style;
  final StrutStyle? strutStyle;
  final TextAlign? textAlign;
  final TextDirection? textDirection;
  final Locale? locale;
  final bool? softWrap;
  final TextOverflow? overflow;
  final TextScaler? textScaler;
  final int? maxLines;
  final String? semanticsLabel;
  final TextWidthBasis? textWidthBasis;
  final TextHeightBehavior? textHeightBehavior;
  final Color? selectionColor;

  @override
  Widget build(BuildContext context) {
    final code = himateLocaleCode(Localizations.localeOf(context));
    return material.Text(
      HimateI18n.literal(code, data),
      style: style,
      strutStyle: strutStyle,
      textAlign: textAlign,
      textDirection: textDirection,
      locale: locale,
      softWrap: softWrap,
      overflow: overflow,
      textScaler: textScaler,
      maxLines: maxLines,
      semanticsLabel: semanticsLabel,
      textWidthBasis: textWidthBasis,
      textHeightBehavior: textHeightBehavior,
      selectionColor: selectionColor,
    );
  }
}

String uiLiteralFor(BuildContext context, String value) =>
    HimateI18n.literal(himateLocaleCode(Localizations.localeOf(context)), value);

String uiLiteral(String value) => HimateI18n.literal(HimateI18n.activeLocale, value);

class HimateI18n {
  static String activeLocale = 'en_US';

  static const Map<String, Map<String, String>> _values = {
    'en_US': {
      'account': 'Account',
      'profile': 'Profile',
      'signOut': 'Sign out',
      'language': 'Language',
      'englishUS': 'English (US)',
      'hungarian': 'Magyar',
      'fullName': 'Full name',
      'jobTitle': 'Job title',
      'phone': 'Phone',
      'timezone': 'Time zone',
      'saveChanges': 'Save changes',
      'profileUpdated': 'Profile updated',
      'profileIntro': 'Personal settings for your HIMATE account.',
      'systemOwner': 'System Owner',
      'systemOwnerHint': 'This account can create users and manage access.',
      'roles': 'Roles',
      'passwordSecurity': 'Password & security',
      'currentPassword': 'Current password',
      'newPassword': 'New password',
      'confirmPassword': 'Confirm new password',
      'changePassword': 'Change password',
      'passwordChanged': 'Password changed. Other sessions were invalidated.',
      'passwordsMismatch': 'The new passwords do not match.',
      'passwordMin': 'Use at least 12 characters.',
      'passwordPolicy': 'Use at least 12 characters with lowercase, uppercase, a number and a special character.',
      'cancel': 'Cancel',
      'close': 'Close',
      'welcomeBack': 'Welcome back',
      'signInSubtitle': 'Sign in to your HIMATE System account',
      'emailAddress': 'Email address',
      'password': 'Password',
      'rememberMe': 'Remember me',
      'forgotPassword': 'Forgot password?',
      'signIn': 'Sign in',
      'showPassword': 'Show password',
      'hidePassword': 'Hide password',
      'enterCredentials': 'Enter your administrator email and password.',
      'recoveryPending': 'Password recovery will be connected in the security phase.',
      'ssoPending': 'SSO is not configured for this environment yet.',
      'nav.dashboard': 'Dashboard',
      'nav.dashboardSub': 'Platform overview',
      'nav.partners': 'Partners',
      'nav.partnersSub': 'Partner control',
      'nav.finance': 'Licensing & Finance',
      'nav.financeSub': 'Commercial management',
      'nav.impact': 'Impact & Reports',
      'nav.impactSub': 'Metrics and reporting',
      'nav.website': 'Website & Marketing',
      'nav.websiteSub': 'Brand and growth',
      'nav.system': 'System & Operations',
      'nav.systemSub': 'Infrastructure health',
      'nav.admin': 'Administration',
      'nav.adminSub': 'Roles and control',
    },
    'hu_HU': {
      'account': 'Fiók',
      'profile': 'Profil',
      'signOut': 'Kijelentkezés',
      'language': 'Nyelv',
      'englishUS': 'Angol (USA)',
      'hungarian': 'Magyar',
      'fullName': 'Teljes név',
      'jobTitle': 'Munkakör',
      'phone': 'Telefonszám',
      'timezone': 'Időzóna',
      'saveChanges': 'Módosítások mentése',
      'profileUpdated': 'Profil frissítve',
      'profileIntro': 'A HIMATE-fiók személyes beállításai.',
      'systemOwner': 'Rendszertulajdonos',
      'systemOwnerHint': 'Ez a fiók hozhat létre felhasználókat és kezelheti a hozzáféréseket.',
      'roles': 'Szerepkörök',
      'passwordSecurity': 'Jelszó és biztonság',
      'currentPassword': 'Jelenlegi jelszó',
      'newPassword': 'Új jelszó',
      'confirmPassword': 'Új jelszó megerősítése',
      'changePassword': 'Jelszó módosítása',
      'passwordChanged': 'A jelszó megváltozott. A többi munkamenet érvénytelenítve lett.',
      'passwordsMismatch': 'Az új jelszavak nem egyeznek.',
      'passwordMin': 'Legalább 12 karakter szükséges.',
      'passwordPolicy': 'Használj legalább 12 karaktert, kis- és nagybetűt, számot és speciális karaktert.',
      'cancel': 'Mégse',
      'close': 'Bezárás',
      'welcomeBack': 'Üdv újra',
      'signInSubtitle': 'Jelentkezz be a HIMATE System fiókodba',
      'emailAddress': 'E-mail-cím',
      'password': 'Jelszó',
      'rememberMe': 'Maradjak bejelentkezve',
      'forgotPassword': 'Elfelejtetted a jelszót?',
      'signIn': 'Bejelentkezés',
      'showPassword': 'Jelszó megjelenítése',
      'hidePassword': 'Jelszó elrejtése',
      'enterCredentials': 'Add meg az adminisztrátori e-mail-címedet és jelszavadat.',
      'recoveryPending': 'A jelszó-helyreállítás a biztonsági fázisban kerül bekötésre.',
      'ssoPending': 'Ebben a környezetben az SSO még nincs konfigurálva.',
      'nav.dashboard': 'Irányítópult',
      'nav.dashboardSub': 'Platform áttekintése',
      'nav.partners': 'Partnerek',
      'nav.partnersSub': 'Partnerkezelés',
      'nav.finance': 'Licencelés és pénzügy',
      'nav.financeSub': 'Kereskedelmi kezelés',
      'nav.impact': 'Hatás és jelentések',
      'nav.impactSub': 'Mérőszámok és riportok',
      'nav.website': 'Weboldal és marketing',
      'nav.websiteSub': 'Márka és növekedés',
      'nav.system': 'Rendszer és üzemeltetés',
      'nav.systemSub': 'Infrastruktúra állapota',
      'nav.admin': 'Adminisztráció',
      'nav.adminSub': 'Szerepkörök és kontroll',
    },
  };


  static const Map<String, String> _literalHu = <String, String>{
    'Dashboard': 'Irányítópult',
    'Partners': 'Partnerek',
    'Partner': 'Partner',
    'Licensing & Finance': 'Licencelés és pénzügy',
    'Impact & Reports': 'Hatás és jelentések',
    'Website & Marketing': 'Weboldal és marketing',
    'System & Operations': 'Rendszer és üzemeltetés',
    'Administration': 'Adminisztráció',
    'Welcome to HIMATE System': 'Üdvözlünk a HIMATE Systemben',
    'Manage partners, programs and cultural impact — all in one place.': 'Kezeld egy helyen a partnereket, programokat és a kulturális hatást.',
    'Manage partners, programs, and cultural impact — all in one place.': 'Kezeld egy helyen a partnereket, programokat és a kulturális hatást.',
    'Active Partners': 'Aktív partnerek',
    'Active Programs': 'Aktív programok',
    'Revenue (YTD)': 'Bevétel (YTD)',
    'People Reached': 'Elért emberek',
    'Recent Activity': 'Legutóbbi tevékenység',
    'Program Impact': 'Programhatás',
    'This Year': 'Idén',
    'View all': 'Összes megtekintése',
    'New partner registered': 'Új partner regisztrálva',
    'Program updated': 'Program frissítve',
    'Payment received': 'Fizetés beérkezett',
    'New user added': 'Új felhasználó hozzáadva',
    'Partner activity': 'Partnertevékenység',
    'Module catalog activity': 'Modulkatalógus-tevékenység',
    'Billing activity': 'Pénzügyi tevékenység',
    'Administration activity': 'Adminisztrációs tevékenység',
    'Partner portfolio': 'Partnerportfólió',
    'New Partner': 'Új partner',
    'Search partners...': 'Partnerek keresése...',
    'All categories': 'Minden kategória',
    'All lifecycle states': 'Minden életciklus-állapot',
    'All health states': 'Minden egészségi állapot',
    'Reference partner': 'Referenciapartner',
    'Reference partners': 'Referenciapartnerek',
    'Live partners': 'Élő partnerek',
    'Prospects': 'Érdeklődők',
    'Partner could not be opened': 'A partner nem nyitható meg',
    'Partner workspace unavailable': 'A partner munkaterülete nem érhető el',
    'Open workspace': 'Munkaterület megnyitása',
    'Partner Health': 'Partnerállapot',
    'Company Data': 'Cégadatok',
    'Company data': 'Cégadatok',
    'Finance & Documents': 'Pénzügy és dokumentumok',
    'Partner Modules': 'Partnermodulok',
    'Statistics': 'Statisztikák',
    'System & Environment': 'Rendszer és környezet',
    'Commercial terms': 'Kereskedelmi feltételek',
    'Commercial Rules': 'Kereskedelmi szabályok',
    'Commercial evidence and internal invoice records for this partner.': 'A partner kereskedelmi bizonyítékai és belső számlarekordjai.',
    'Legal name': 'Hivatalos cégnév',
    'Brand / DBA': 'Márkanév / DBA',
    'Registration number': 'Cégjegyzékszám',
    'Tax ID': 'Adóazonosító',
    'Primary contact': 'Elsődleges kapcsolattartó',
    'Primary email': 'Elsődleges e-mail',
    'Finance contact': 'Pénzügyi kapcsolattartó',
    'Finance email': 'Pénzügyi e-mail',
    'Technical contact': 'Technikai kapcsolattartó',
    'Technical email': 'Technikai e-mail',
    'Marketing contact': 'Marketing kapcsolattartó',
    'Marketing email': 'Marketing e-mail',
    'Country': 'Ország',
    'State / region': 'Állam / régió',
    'City': 'Város',
    'Postal code': 'Irányítószám',
    'Address line 1': 'Cím 1. sor',
    'Address line 2': 'Cím 2. sor',
    'Website': 'Weboldal',
    'Phone': 'Telefon',
    'Notes': 'Megjegyzések',
    'Edit partner': 'Partner szerkesztése',
    'Save changes': 'Módosítások mentése',
    'Lifecycle': 'Életciklus',
    'Lifecycle change reason': 'Életciklus-váltás indoka',
    'Module catalog': 'Modulkatalógus',
    'Canonical Module Catalog': 'Kanonikus modulkatalógus',
    'Search module catalog...': 'Keresés a modulkatalógusban...',
    'Search modules...': 'Modulok keresése...',
    'All groups': 'Minden csoport',
    'Availability': 'Elérhetőség',
    'Add custom module': 'Egyedi modul hozzáadása',
    'Add module': 'Modul hozzáadása',
    'Create module': 'Modul létrehozása',
    'Module name': 'Modul neve',
    'Module name *': 'Modul neve *',
    'Stable technical key': 'Stabil technikai kulcs',
    'Stable key *': 'Stabil kulcs *',
    'Menu group': 'Menücsoport',
    'Description': 'Leírás',
    'Default monthly price (USD)': 'Alap havi ár (USD)',
    'Default 30-day price': 'Alap 30 napos ár',
    'Visibility is separate from module code existence.': 'A láthatóság független a modul kódjának létezésétől.',
    'Module state': 'Modulállapot',
    'Visible for partner': 'Partner számára látható',
    'Included in base package': 'Alapcsomag része',
    'Partner 30-day price': 'Partner 30 napos ára',
    'Change reason': 'Módosítás indoka',
    'Price effective at': 'Ár érvényességének kezdete',
    'Cancel at period end': 'Lemondás az időszak végén',
    'Billing profile': 'Számlázási profil',
    'Edit billing profile': 'Számlázási profil szerkesztése',
    'Bank name': 'Bank neve',
    'Bank address': 'Bank címe',
    'Account number': 'Bankszámlaszám',
    'IBAN': 'IBAN',
    'SWIFT / BIC': 'SWIFT / BIC',
    'Save billing profile': 'Számlázási profil mentése',
    'Activation fee': 'Aktiválási díj',
    'Activation fee · USD': 'Aktiválási díj · USD',
    'Activation fee waived': 'Aktiválási díj elengedve',
    'Base monthly fee': 'Alap havi díj',
    'Base monthly fee · USD': 'Alap havi díj · USD',
    'Annual increase %': 'Éves emelés %',
    'Service activation / anchor date': 'Szolgáltatás aktiválási / horgonydátuma',
    'License status': 'Licenc állapota',
    'License paid': 'Licenc kifizetve',
    'Paid amount': 'Kifizetett összeg',
    'Payment date': 'Fizetés dátuma',
    'Payment reference': 'Fizetési hivatkozás',
    'Payment evidence': 'Fizetési bizonyíték',
    'Document name *': 'Dokumentum neve *',
    'Document type': 'Dokumentumtípus',
    'Storage URL / reference': 'Tárolási URL / hivatkozás',
    'Register document': 'Dokumentum rögzítése',
    'Invoices': 'Számlák',
    'Documents': 'Dokumentumok',
    'Impact Summary': 'Hatásösszesítő',
    'Metric Definitions': 'Mérőszám-definíciók',
    'New metric': 'Új mérőszám',
    'Metric key': 'Mérőszám kulcsa',
    'Unit': 'Mértékegység',
    'Aggregation': 'Aggregáció',
    'Scope': 'Hatókör',
    'Baseline': 'Bázisérték',
    'Baseline value': 'Bázisérték',
    'Baseline period start': 'Bázisidőszak kezdete',
    'Baseline period end': 'Bázisidőszak vége',
    'Set baseline': 'Bázisérték beállítása',
    'Save baseline': 'Bázisérték mentése',
    'Record impact value': 'Hatásérték rögzítése',
    'Record value': 'Érték rögzítése',
    'Numeric value': 'Számérték',
    'Period start': 'Időszak kezdete',
    'Period end': 'Időszak vége',
    'Source reference': 'Forráshivatkozás',
    'Evidence': 'Bizonyíték',
    'Evidence Library': 'Bizonyítéktár',
    'Upload Evidence': 'Bizonyíték feltöltése',
    'Create evidence': 'Bizonyíték létrehozása',
    'Evidence title *': 'Bizonyíték címe *',
    'Evidence type': 'Bizonyíték típusa',
    'Linked metric': 'Kapcsolt mérőszám',
    'Verification': 'Ellenőrzés',
    'Verified': 'Ellenőrzött',
    'Unverified': 'Nem ellenőrzött',
    'Rejected': 'Elutasított',
    'Uploaded': 'Feltöltve',
    'Uploaded by': 'Feltöltötte',
    'Verified by': 'Ellenőrizte',
    'Download': 'Letöltés',
    'Preview': 'Előnézet',
    'Reports': 'Jelentések',
    'Generate Report': 'Jelentés készítése',
    'Generate PDF report': 'PDF-jelentés készítése',
    'Report type': 'Jelentés típusa',
    'Report title': 'Jelentés címe',
    'Partner Impact Report': 'Partnerhatás-jelentés',
    'Multi-Partner Report': 'Többpartneres jelentés',
    'HIMATE Global Impact Report': 'HIMATE globális hatásjelentés',
    'Queue report': 'Jelentés sorba állítása',
    'Download PDF': 'PDF letöltése',
    'Regenerate snapshot': 'Pillanatkép újragenerálása',
    'HIMATE CMS': 'HIMATE CMS',
    'CMS Pages': 'CMS-oldalak',
    'Media Assets': 'Médiaelemek',
    'Upload media': 'Média feltöltése',
    'New CMS page': 'Új CMS-oldal',
    'Create draft': 'Vázlat létrehozása',
    'Edit draft': 'Vázlat szerkesztése',
    'Publish': 'Publikálás',
    'Published': 'Publikálva',
    'Draft': 'Vázlat',
    'Version history ·': 'Verzióelőzmények ·',
    'Audit': 'Audit',
    'Page key': 'Oldalkulcs',
    'Admin page name *': 'Adminoldal neve *',
    'Slug *': 'Slug *',
    'SEO title': 'SEO-cím',
    'SEO title * for publish': 'SEO-cím * publikáláshoz',
    'Meta description': 'Meta leírás',
    'Meta description * for publish': 'Meta leírás * publikáláshoz',
    'Canonical HTTPS URL': 'Kanonikus HTTPS URL',
    'Canonical HTTPS URL * for publish': 'Kanonikus HTTPS URL * publikáláshoz',
    'Open Graph title': 'Open Graph cím',
    'Open Graph description': 'Open Graph leírás',
    'Open Graph image': 'Open Graph kép',
    'Noindex': 'Noindex',
    'Content sections': 'Tartalmi szekciók',
    'Add section': 'Szekció hozzáadása',
    'Section ID *': 'Szekcióazonosító *',
    'Component type': 'Komponenstípus',
    'Heading * when visible': 'Címsor * ha látható',
    'Body': 'Törzsszöveg',
    'Media asset': 'Médiaelem',
    'CTA label': 'CTA felirat',
    'CTA URL': 'CTA URL',
    'Visible': 'Látható',
    'Move up': 'Mozgatás felfelé',
    'Move down': 'Mozgatás lefelé',
    'Remove from draft': 'Eltávolítás a vázlatból',
    'Contact Leads': 'Kapcsolati érdeklődők',
    'Contact lead': 'Kapcsolati érdeklődő',
    'Search leads': 'Érdeklődők keresése',
    'Lead status': 'Érdeklődő állapota',
    'All statuses': 'Minden állapot',
    'Assigned to': 'Felelős',
    'Name or team': 'Név vagy csapat',
    'Name, organization, email or message': 'Név, szervezet, e-mail vagy üzenet',
    'Inquiry': 'Megkeresés',
    'Internal follow-up note': 'Belső utánkövetési jegyzet',
    'Record next step, outcome or context': 'Rögzítsd a következő lépést, eredményt vagy kontextust',
    'Save lead': 'Érdeklődő mentése',
    'No contact leads': 'Nincsenek kapcsolati érdeklődők',
    'New website inquiries will appear here automatically.': 'Az új weboldali megkeresések automatikusan itt jelennek meg.',
    'Contact Leads unavailable': 'A kapcsolati érdeklődők nem érhetők el',
    'Website inquiries stored in HIMATE with follow-up status, owner and internal notes.': 'A weboldali megkeresések utánkövetési állapottal, felelőssel és belső jegyzetekkel kerülnek a HIMATE-be.',
    'Email contact': 'E-mail küldése',
    'Contact lead updated.': 'A kapcsolati érdeklődő frissítve.',
    'System Health': 'Rendszerállapot',
    'Service Health': 'Szolgáltatásállapot',
    'Architecture': 'Architektúra',
    'Containerization': 'Konténerizáció',
    'Horizontal scaling': 'Horizontális skálázás',
    'Private services': 'Privát szolgáltatások',
    'Public ingress': 'Nyilvános belépési pont',
    'Partner databases': 'Partner-adatbázisok',
    'Persistence': 'Perzisztencia',
    'Operational Controls': 'Üzemeltetési vezérlők',
    'Provisioning': 'Provisioning',
    'Provisioning Engine': 'Provisioning motor',
    'Environments': 'Környezetek',
    'Environment': 'Környezet',
    'Connector': 'Connector',
    'Integrations': 'Integrációk',
    'Domains & Deployments': 'Domainek és telepítések',
    'Deployment': 'Telepítés',
    'Deployment status': 'Telepítési állapot',
    'Production environment': 'Éles környezet',
    'Production hostname': 'Éles hosztnév',
    'Production hostname *': 'Éles hosztnév *',
    'Verify DNS/TLS': 'DNS/TLS ellenőrzése',
    'Deploy': 'Telepítés',
    'Launch production': 'Éles indítás',
    'Go LIVE': 'Élesítés',
    'Backups & Recoverability': 'Biztonsági mentések és helyreállíthatóság',
    'Backup policy': 'Mentési szabályzat',
    'Automatic backups': 'Automatikus mentések',
    'Automatic backups enabled': 'Automatikus mentés engedélyezve',
    'Retention days': 'Megőrzési napok',
    'Max restore points': 'Maximális visszaállítási pontok',
    'Automatic backup interval (hours)': 'Automatikus mentési időköz (óra)',
    'Save policy': 'Szabályzat mentése',
    'Create restore point': 'Visszaállítási pont létrehozása',
    'Run restore test': 'Visszaállítási teszt futtatása',
    'Restore test': 'Visszaállítási teszt',
    'Restore tested': 'Visszaállítás tesztelve',
    'Offsite provider': 'Külső mentési szolgáltató',
    'Roles & Permissions': 'Szerepkörök és jogosultságok',
    'Role Matrix': 'Szerepkörmátrix',
    'Administrators': 'Adminisztrátorok',
    'Add administrator': 'Adminisztrátor hozzáadása',
    'Create administrator': 'Adminisztrátor létrehozása',
    'Edit administrator access': 'Adminisztrátori hozzáférés szerkesztése',
    'Full name': 'Teljes név',
    'Email address': 'E-mail-cím',
    'Temporary password': 'Ideiglenes jelszó',
    'New password (optional)': 'Új jelszó (opcionális)',
    'Roles': 'Szerepkörök',
    'Active account': 'Aktív fiók',
    'Effective permissions': 'Tényleges jogosultságok',
    'Administrative Event Stream': 'Adminisztratív eseménynapló',
    'Search audit history': 'Keresés az auditnaplóban',
    'All methods': 'Minden metódus',
    'All outcomes': 'Minden eredmény',
    'All resources': 'Minden erőforrás',
    'Actor': 'Végrehajtó',
    'Request ID': 'Kérésazonosító',
    'Resource': 'Erőforrás',
    'Outcome': 'Eredmény',
    'Duration': 'Időtartam',
    'HTTP status': 'HTTP-állapot',
    'Status': 'Állapot',
    'State': 'Állapot',
    'Health': 'Állapot',
    'Healthy': 'Egészséges',
    'Warning': 'Figyelmeztetés',
    'Offline': 'Offline',
    'Error': 'Hiba',
    'Success': 'Siker',
    'Active': 'Aktív',
    'Inactive': 'Inaktív',
    'Maintenance': 'Karbantartás',
    'Not licensed': 'Nincs licencelve',
    'Configure': 'Konfigurálás',
    'Apply': 'Alkalmazás',
    'Next': 'Tovább',
    'Previous': 'Vissza',
    'Refresh': 'Frissítés',
    'Close': 'Bezárás',
    'Cancel': 'Mégse',
    'Copy': 'Másolás',
    'Edit access': 'Hozzáférés szerkesztése',
    'Open URL': 'URL megnyitása',
    'Search anywhere...': 'Keresés bárhol...',
    'Search Evidence': 'Bizonyíték keresése',
    'No administrators found': 'Nem található adminisztrátor',
    'No matching audit events': 'Nincs egyező auditesemény',
    'No partner data': 'Nincs partneradat',
    'No module data': 'Nincs moduladat',
    'No impact data': 'Nincs hatásadat',
    'No reports yet': 'Még nincs jelentés',
    'No CMS pages yet': 'Még nincs CMS-oldal',
    'No CMS media yet': 'Még nincs CMS-média',
    'No service health data': 'Nincs szolgáltatásállapot-adat',
    'No environment yet': 'Még nincs környezet',
    'No connector credential yet': 'Még nincs Connector-hitelesítő adat',
    'No documents registered': 'Nincs regisztrált dokumentum',
    'No invoice records yet': 'Még nincs számlarekord',
    'You are already signed in.': 'Már be vagy jelentkezve.',
    'Continue to the HIMATE administration platform.': 'Folytatás a HIMATE adminisztrációs platformra.',
    'Open admin platform': 'Adminplatform megnyitása',
    'Workspace prepared': 'Munkaterület előkészítve',
    'Good morning,': 'Jó reggelt,',
    'Good afternoon,': 'Jó napot,',
    'Good evening,': 'Jó estét,',
    'PLATFORM OPERATIONS': 'PLATFORMÜZEMELTETÉS',
    'WEBSITE & MARKETING': 'WEBOLDAL ÉS MARKETING',
    'COMMERCIAL CONTROL': 'KERESKEDELMI VEZÉRLÉS',
    'IMPACT CONTROL': 'HATÁSVEZÉRLÉS',
    'ADMINISTRATION': 'ADMINISZTRÁCIÓ',
    'NEW PARTNER': 'ÚJ PARTNER',
    'READY': 'KÉSZ',
    'FAILED': 'SIKERTELEN',
    'QUEUED': 'SORBAN',
    'DEPLOYING': 'TELEPÍTÉS FOLYAMATBAN',
    'DEPLOYED': 'TELEPÍTVE',
    'NOT DEPLOYED': 'NINCS TELEPÍTVE',
    'UNAVAILABLE': 'NEM ELÉRHETŐ',
    'DEPRECATED': 'KIVEZETETT',
    'SUSPENDED': 'FELFÜGGESZTVE',
    'TESTING': 'TESZTELÉS',
    'LIVE': 'ÉLES',
  };

  static const Map<String, String> _fallbackHu = <String, String>{
    'Partner workspace': 'Partner munkaterület',
    'partner workspace': 'partner munkaterület',
    'Partner environments': 'Partnerkörnyezetek',
    'partner environments': 'partnerkörnyezetek',
    'Website inquiries': 'Weboldali megkeresések',
    'website inquiries': 'weboldali megkeresések',
    'Contact leads': 'Kapcsolati érdeklődők',
    'contact leads': 'kapcsolati érdeklődők',
    'Restore point': 'Visszaállítási pont',
    'restore point': 'visszaállítási pont',
    'Restore test': 'Visszaállítási teszt',
    'restore test': 'visszaállítási teszt',
    'Evidence': 'Bizonyíték',
    'evidence': 'bizonyíték',
    'Reports': 'Jelentések',
    'reports': 'jelentések',
    'Report': 'Jelentés',
    'report': 'jelentés',
    'Metrics': 'Mérőszámok',
    'metrics': 'mérőszámok',
    'Metric': 'Mérőszám',
    'metric': 'mérőszám',
    'Modules': 'Modulok',
    'modules': 'modulok',
    'Module': 'Modul',
    'module': 'modul',
    'Environment': 'Környezet',
    'environment': 'környezet',
    'Deployment': 'Telepítés',
    'deployment': 'telepítés',
    'Configuration': 'Konfiguráció',
    'configuration': 'konfiguráció',
    'Status': 'Állapot',
    'status': 'állapot',
    'Health': 'Állapot',
    'health': 'állapot',
    'Version': 'Verzió',
    'version': 'verzió',
    'Created': 'Létrehozva',
    'created': 'létrehozva',
    'Updated': 'Frissítve',
    'updated': 'frissítve',
    'Current': 'Aktuális',
    'current': 'aktuális',
    'Next': 'Következő',
    'next': 'következő',
    'Previous': 'Előző',
    'previous': 'előző',
    'Search': 'Keresés',
    'search': 'keresés',
    'Name': 'Név',
    'name': 'név',
    'Email': 'E-mail',
    'email': 'e-mail',
    'Organization': 'Szervezet',
    'organization': 'szervezet',
    'Message': 'Üzenet',
    'message': 'üzenet',
    'Assigned': 'Felelős',
    'assigned': 'felelős',
    'Records': 'Rekordok',
    'records': 'rekordok',
    'Record': 'Rekord',
    'record': 'rekord',
  };



  static const Map<String, String> _extendedHu = <String, String>{
    'Culture Connects People': 'A kultúra összeköti az embereket',
    'or continue with': 'vagy folytasd ezzel',
    'Sign in with SSO': 'Bejelentkezés SSO-val',
    'Secure  •  Trusted  •  Built for a brighter tomorrow': 'Biztonságos  •  Megbízható  •  Egy fényesebb holnapra építve',
    'The brand system and responsive shell are ready. Functional implementation remains in its scheduled START cycle.': 'Az arculati rendszer és a reszponzív keret kész. A funkcionális megvalósítás az ütemezett START ciklusban folytatódik.',
    'Create a partner category first.': 'Előbb hozz létre partnerkategóriát.',
    '1 · Business identity': '1 · Üzleti identitás',
    'Add category': 'Kategória hozzáadása',
    'Unknown': 'Ismeretlen',
    'Move the partner to READY TO PROVISION before starting provisioning.': 'Állítsd a partnert READY TO PROVISION állapotba a provisioning megkezdése előtt.',
    'Store this credential now': 'Hitelesítő adat biztonságos mentése',
    'For security, HIMATE stores only the token hash. This raw credential will not be shown again.': 'Biztonsági okból a HIMATE csak a token hashét tárolja. A nyers hitelesítő adat később nem jelenik meg újra.',
    'Credential copied.': 'Hitelesítő adat másolva.',
    'I stored it securely': 'Biztonságosan elmentettem',
    'Use only for an existing/reference partner where no activation transaction applies.': 'Csak meglévő vagy referenciapartnernél használd, ahol nincs aktiválási tranzakció.',
    'Contract': 'Szerződés',
    'Invoice': 'Számla',
    'Receipt': 'Bizonylat',
    'Other': 'Egyéb',
    'All states': 'Minden állapot',
    'Generate / rotate credential': 'Hitelesítő adat létrehozása / cseréje',
    'Image': 'Kép',
    'Screenshot': 'Képernyőkép',
    'URL reference': 'URL-hivatkozás',
    'Partner declaration': 'Partnernyilatkozat',
    'Choose file': 'Fájl kiválasztása',
    'All types': 'Minden típus',
    'Integrity': 'Integritás',
    'Verify': 'Ellenőrzés',
    'Failed': 'Sikertelen',
    'Monthly': 'Havi',
    'Partner category': 'Partnerkategória',
    'Primary domain': 'Elsődleges domain',
    'Verified paid amount · USD': 'Ellenőrzött kifizetett összeg · USD',
    'Desired platform release': 'Kívánt platformkiadás',
    'Category': 'Kategória',
    'Desired release': 'Kívánt kiadás',
    'Active release': 'Aktív kiadás',
    'Staging domain': 'Staging domain',
    'Logo URL / asset reference': 'Logó URL / elemhivatkozás',
    'Internal notes': 'Belső megjegyzések',
    'Currency': 'Pénznem',
    'Initial license / activation fee': 'Kezdeti licenc / aktiválási díj',
    'Waiver reason': 'Elengedés indoka',
    'License note': 'Licenc megjegyzés',
    'Base 30-day service fee': 'Alap 30 napos szolgáltatási díj',
    'Price effective from': 'Ár érvényességének kezdete',
    'Billing contact': 'Számlázási kapcsolattartó',
    'Company address': 'Cég címe',
    'Billing phone': 'Számlázási telefonszám',
    'Display label': 'Megjelenített felirat',
    'Partner ID': 'Partnerazonosító',
    'Partner ID *': 'Partnerazonosító *',
    'HTTP(S) source URL *': 'HTTP(S) forrás URL *',
    'Partner declaration *': 'Partnernyilatkozat *',
    'Verified numeric value': 'Ellenőrzött számérték',
    'Type': 'Típus',
    'Period from': 'Időszak kezdete',
    'Period to': 'Időszak vége',
    'Method': 'Metódus',
    'e.g. Cultural Foundation': 'pl. Kulturális Alapítvány',
    'Optional RFC3339 timestamp': 'Opcionális RFC3339 időbélyeg',
    'Leave empty for global baseline': 'Hagyd üresen globális bázisértékhez',
    'Actor, request ID, resource, path or partner': 'Végrehajtó, kérésazonosító, erőforrás, útvonal vagy partner',
    'Edit commercial terms': 'Kereskedelmi feltételek szerkesztése',
    'HIMATE System': 'HIMATE System',
    'Independent services behind one authenticated public gateway.': 'Független szolgáltatások egy hitelesített nyilvános gateway mögött.',
    'Refreshing operations data': 'Üzemeltetési adatok frissítése',
    'Dashboard data is temporarily unavailable': 'Az irányítópult adatai átmenetileg nem érhetők el',
    'Add partner category': 'Partnerkategória hozzáadása',
    'New Partner · Provisioning Wizard': 'Új partner · Provisioning varázsló',
    'Partners could not be loaded': 'A partnerek nem tölthetők be',
    'Connector credential': 'Connector hitelesítő adat',
    'Generate or rotate a partner-scoped credential. The raw secret is displayed exactly once.': 'Hozz létre vagy cserélj partnerhez kötött hitelesítő adatot. A nyers titok pontosan egyszer jelenik meg.',
    'Edit legal identity, contacts, lifecycle and partner references.': 'Jogi identitás, kapcsolattartók, életciklus és partnerhivatkozások szerkesztése.',
    'Pricing & Subscription': 'Árazás és előfizetés',
    'Partner-specific license and recurring terms with an activation-date anchored 30-day service cycle.': 'Partnerspecifikus licenc- és ismétlődő feltételek, az aktiválási dátumhoz rögzített 30 napos szolgáltatási ciklussal.',
    'Register commercial document metadata with a persistent storage URL or document reference.': 'Kereskedelmi dokumentum metaadatainak rögzítése tartós tárolási URL-lel vagy dokumentumhivatkozással.',
    'Secondary data is loading independently': 'A másodlagos adatok külön töltődnek',
    'Workspace': 'Munkaterület',
    'Provisioning state, isolated partner infrastructure, staging/production and release metadata.': 'Provisioning állapot, elkülönített partner-infrastruktúra, staging/production és kiadási metaadatok.',
    'Entitlement, visibility, base-package inclusion and partner-specific pricing.': 'Jogosultság, láthatóság, alapcsomag-tagság és partnerspecifikus árazás.',
    'No impact observations yet': 'Még nincs hatásmegfigyelés',
    'Partner-scoped Connector Protocol credentials. Raw secrets are never stored by HIMATE.': 'Partnerhez kötött Connector Protocol hitelesítő adatok. A HIMATE soha nem tárol nyers titkokat.',
    'HIMATE billing profile': 'HIMATE számlázási profil',
    'Issuer and international banking data used as the foundation for future invoice-provider integration.': 'Kibocsátói és nemzetközi banki adatok a későbbi számlázási szolgáltatói integráció alapjaként.',
    'Manage catalog metadata and availability without changing the stable technical key.': 'Katalógusmetaadatok és elérhetőség kezelése a stabil technikai kulcs módosítása nélkül.',
    'Finance workspace unavailable': 'A pénzügyi munkaterület nem érhető el',
    'Manual values remain distinct from connector and verified-document provenance.': 'A kézi értékek elkülönülnek a connector- és ellenőrzött dokumentum eredetétől.',
    'Store an explicit baseline period and value for reproducible comparison.': 'Rögzíts explicit bázisidőszakot és értéket a reprodukálható összehasonlításhoz.',
    'Impact data unavailable': 'A hatásadatok nem érhetők el',
    'Partner, multi-partner and HIMATE Global PDFs generated from frozen, auditable snapshots.': 'Partner-, többpartneres és HIMATE Global PDF-ek rögzített, auditálható pillanatképekből.',
    'Stable definitions reused by manual entry, connectors and verified-document workflows.': 'Stabil definíciók, amelyeket a kézi bevitel, connectorok és ellenőrzött dokumentumfolyamatok is újrahasználnak.',
    'No cached operations data yet': 'Még nincs gyorsítótárazott üzemeltetési adat',
    'Operations data unavailable': 'Az üzemeltetési adatok nem érhetők el',
    'Readiness and liveness are monitored independently for each microservice.': 'A readiness és liveness minden mikroszolgáltatásnál külön felügyelt.',
    'Idempotent jobs can resume after interruption without creating duplicate partner infrastructure.': 'Az idempotens feladatok megszakítás után folytathatók duplikált partner-infrastruktúra létrehozása nélkül.',
    'Central audit history, administrator lifecycle, roles and backend-enforced permissions across the HIMATE control plane.': 'Központi auditnapló, adminisztrátori életciklus, szerepkörök és backend által kikényszerített jogosultságok a HIMATE vezérlősíkján.',
    'Audit history could not be loaded': 'Az auditnapló nem tölthető be',
    'HIMATE Issuer Profile': 'HIMATE kibocsátói profil',
    'No cached operations snapshot is available yet. The page is ready and data will appear automatically.': 'Még nincs elérhető gyorsítótárazott üzemeltetési pillanatkép. Az oldal kész, az adatok automatikusan megjelennek.',
    'Sign out': 'Kijelentkezés',
    'Provisioning creates the staging connector identity automatically. You can also generate or rotate it here.': 'A provisioning automatikusan létrehozza a staging connector identitását. Itt külön is létrehozhatod vagy cserélheted.',
    'Upload a PDF, image, invoice, contract, screenshot, URL or partner declaration.': 'Tölts fel PDF-et, képet, számlát, szerződést, képernyőképet, URL-t vagy partnernyilatkozatot.',
    'Mutating administration actions will appear here automatically. Adjust the filters if you are looking for earlier activity.': 'A módosító adminisztrációs műveletek automatikusan megjelennek itt. Korábbi aktivitáshoz módosítsd a szűrőket.',
    'PEOPLE  |  PROGRAMS  |  IMPACT': 'EMBEREK  |  PROGRAMOK  |  HATÁS',
    'Create & validate provisioning': 'Provisioning létrehozása és ellenőrzése',
    'Generate credential': 'Hitelesítő adat létrehozása',
    'Save commercial terms': 'Kereskedelmi feltételek mentése',
    'Base package': 'Alapcsomag',
    'Release': 'Kiadás',
    'Last error': 'Legutóbbi hiba',
    'Value': 'Érték',
    'Latest period': 'Legutóbbi időszak',
    'Observations': 'Megfigyelések',
    'Credential ID': 'Hitelesítő azonosító',
    'Rotated': 'Cserélve',
    'Last used': 'Legutóbb használva',
    'Priced defaults': 'Árazott alapértékek',
    'Annual uplift': 'Éves emelés',
    'Delta': 'Eltérés',
    'Period': 'Időszak',
    'Template': 'Sablon',
    'Snapshot': 'Pillanatkép',
    'Key': 'Kulcs',
    'Overall': 'Összesített',
    'Partner DB': 'Partner-adatbázis',
    'Storage': 'Tárolás',
    'Data sync': 'Adatszinkronizáció',
    'Last sync': 'Legutóbbi szinkron',
    'System': 'Rendszer',
    'Registration': 'Regisztráció',
    'Annual increase': 'Éves emelés',
    'Billing rule': 'Számlázási szabály',
    'Bank': 'Bank',
    'Service period': 'Szolgáltatási időszak',
    'Renewal': 'Megújítás',
    'Invoice trigger': 'Számlázási esemény',
    'Annual base-fee uplift': 'Éves alapdíj-emelés',
    'Default uplift': 'Alapértelmezett emelés',
    'External payment provider': 'Külső fizetési szolgáltató',
    'Identity boundary': 'Identitási határ',
    'Partner domain': 'Partner domain',
    'Catalog domain': 'Katalógus domain',
    'Billing domain': 'Számlázási domain',
    'Connector model': 'Connector modell',
    'Backups / restore': 'Biztonsági mentések / helyreállítás',
    'Restore': 'Helyreállítás',
    'CMS audit ·': 'CMS audit ·',
    'No media': 'Nincs média',
    'Edit CMS draft ·': 'CMS-vázlat szerkesztése ·',
    'SEO & routing': 'SEO és útvonalkezelés',
    'Published content stays available but is marked not to be indexed.': 'A publikált tartalom elérhető marad, de noindex jelölést kap.',
    'Section': 'Szekció',
    'Turning this off preserves the section content but removes it from public/preview output.': 'Kikapcsoláskor a szekció tartalma megmarad, de eltűnik a nyilvános és előnézeti kimenetből.',
    'Alt / media description': 'Alt / médialeírás',
    'HIMATE Landing': 'HIMATE nyitóoldal',
    'Describe the image or video for accessibility': 'Írd le a képet vagy videót az akadálymentességhez',
    'Preview media': 'Média előnézete',
    'Create the first immutable draft. Existing public pages remain unchanged until START-17.': 'Hozd létre az első megváltoztathatatlan vázlatot. A jelenlegi nyilvános oldalak publikálásig változatlanok maradnak.',
    'Upload CMS media': 'CMS-média feltöltése',
    'PNG, JPEG, WebP, MP4 or WebM · max 64 MiB · content-sniffed · SHA-256 verified.': 'PNG, JPEG, WebP, MP4 vagy WebM · max. 64 MiB · tartalomellenőrzött · SHA-256-tal ellenőrzött.',
    'CMS unavailable': 'A CMS nem érhető el',
    'Manage published website content, story video, media and SEO without editing source code.': 'Publikált webtartalom, story videó, média és SEO kezelése forráskód szerkesztése nélkül.',
    'Each page keeps independent draft, preview and published snapshots.': 'Minden oldal külön vázlat-, előnézeti és publikált pillanatképet tart fenn.',
    'CMS images and story videos are content-sniffed, checksum-backed and referenced by stable asset ID.': 'A CMS-képek és story videók tartalomellenőrzöttek, ellenőrzőösszeggel védettek és stabil elem-azonosítóval hivatkozottak.',
    'No sections in this draft': 'Nincsenek szekciók ebben a vázlatban',
    'Create a page draft, preview it, then publish it to activate CMS content on the public website.': 'Készíts oldalvázlatot, ellenőrizd előnézetben, majd publikáld a nyilvános weboldal aktiválásához.',
    'Upload an image or MP4/WebM story video before linking media to page sections.': 'Tölts fel képet vagy MP4/WebM story videót, mielőtt médiát kapcsolsz az oldalszekciókhoz.',
    'Add at least one visible section before publishing.': 'Publikálás előtt adj hozzá legalább egy látható szekciót.',
    'File': 'Fájl',
    'Asset ID': 'Elem-azonosító',
    'Alt text': 'Alt szöveg',
    'Suspended administrators cannot sign in or use an existing session.': 'A felfüggesztett adminisztrátorok nem jelentkezhetnek be és meglévő munkamenetet sem használhatnak.',
    'Platform Admin access required': 'Platform Admin hozzáférés szükséges',
    'Roles & Permissions could not be loaded': 'A szerepkörök és jogosultságok nem tölthetők be',
    'Backend-enforced RBAC. Read, write and approval rights are checked before each protected administration API request.': 'Backend által kikényszerített RBAC. Az olvasási, írási és jóváhagyási jogok minden védett adminisztrációs API-kérés előtt ellenőrzésre kerülnek.',
    'Roles are additive. Approval permissions protect sensitive actions such as publishing, verification and provisioning execution.': 'A szerepkörök jogosultságai összeadódnak. A jóváhagyási jogok védik az érzékeny műveleteket, például a publikálást, ellenőrzést és provisioning futtatást.',
    'Accounts are never hard-deleted from administration. Suspend access to preserve audit identity and historical attribution.': 'A fiókokat az adminisztráció soha nem törli véglegesen. Függeszd fel a hozzáférést az auditidentitás és történeti hozzárendelés megőrzéséhez.',
    'Role assignment and administrator lifecycle are protected by backend Administration permissions.': 'A szerepkör-hozzárendelést és az adminisztrátori életciklust backend Administration jogosultságok védik.',
    'Create an administrator to assign a scoped HIMATE role.': 'Hozz létre adminisztrátort egy hatókörrel rendelkező HIMATE szerepkör hozzárendeléséhez.',
    'User ID': 'Felhasználóazonosító',
    'Policy': 'Szabályzat',
    'No provisioned partner available': 'Nincs provisionált partner',
    'Start backup': 'Biztonsági mentés indítása',
    'Backup': 'Biztonsági mentés',
    'Backup completed': 'Biztonsági mentés kész',
    'Retention': 'Megőrzés',
    'Restore-point limit': 'Visszaállítási pontok korlátja',
    'Automatic interval': 'Automatikus időköz',
    'Add production': 'Production hozzáadása',
    'Staging and production release state, DNS/TLS verification and controlled READY FOR LAUNCH → LIVE transition.': 'Staging- és production kiadási állapot, DNS/TLS-ellenőrzés és vezérelt READY FOR LAUNCH → LIVE átmenet.',
    'Create production': 'Production létrehozása',
    'Runtime': 'Futtatókörnyezet',
    'Domain': 'Domain',
    'Domain checked': 'Domain ellenőrizve',
    'Launched by': 'Élesítette',
    'Launched at': 'Élesítés ideje',
    'Notification': 'Értesítés',
    'Culture Fuels Tomorrow.': 'A kultúra táplálja a holnapot.',
  };

  static const Map<String, String> _designHu = <String, String>{
    'Design Guide': 'Arculati útmutató',
    'Global website brand controls for logo, colors, typography, buttons and bilingual navigation.': 'Globális weboldal-arculati beállítások logóhoz, színekhez, tipográfiához, gombokhoz és kétnyelvű navigációhoz.',
    'Brand': 'Arculat',
    'Published globally': 'Globálisan publikálva',
    'Languages': 'Nyelvek',
    'English + Hungarian labels': 'Angol + magyar feliratok',
    'Preview-safe': 'Előnézet-biztos',
    'Draft before publish': 'Vázlat publikálás előtt',
    'Every save/publish recorded': 'Minden mentés és publikálás naplózva',
    'Website logo': 'Weboldal logója',
    'Default HIMATE logo': 'Alapértelmezett HIMATE logó',
    'Primary navy': 'Elsődleges sötétkék',
    'Brand gold': 'Arculati arany',
    'Page background': 'Oldal háttere',
    'Body text color': 'Törzsszöveg színe',
    'Heading font': 'Címsor betűtípusa',
    'Body font': 'Törzsszöveg betűtípusa',
    'Button corner radius': 'Gombsarkok lekerekítése',
    '0–40 pixels': '0–40 képpont',
    'HIMATE website preview': 'HIMATE weboldal előnézet',
    'The published Design Guide is applied without editing source code.': 'A publikált Arculati útmutató forráskód szerkesztése nélkül lép életbe.',
    'Primary action': 'Elsődleges művelet',
    'Website Navigation': 'Weboldal navigáció',
    'Control visible public menu items, bilingual labels and order.': 'A nyilvános menüpontok láthatóságának, kétnyelvű feliratainak és sorrendjének kezelése.',
    'Add navigation item': 'Navigációs elem hozzáadása',
    'No navigation items': 'Nincsenek navigációs elemek',
    'Add at least one item for public navigation.': 'Adj hozzá legalább egy elemet a nyilvános navigációhoz.',
    'Navigation item': 'Navigációs elem',
    'Remove': 'Eltávolítás',
    'English label': 'Angol felirat',
    'Hungarian label': 'Magyar felirat',
    'URL': 'URL',
    'Visible in navigation': 'Látható a navigációban',
    'No Design Guide publication yet': 'Az Arculati útmutató még nincs publikálva',
    'Save design draft': 'Arculati vázlat mentése',
    'Publish design': 'Arculat publikálása',
    'Design draft saved.': 'Az arculati vázlat elmentve.',
    'Design Guide published to the public website.': 'Az Arculati útmutató publikálva a nyilvános weboldalon.',
    'Design settings loaded from defaults': 'Az arculati beállítások alapértékekből betöltve',
    'Use six-digit hexadecimal colors, for example #06172C.': 'Használj hatjegyű hexadecimális színeket, például #06172C.',
    'Button radius must be between 0 and 40.': 'A gombsarkok lekerekítése 0 és 40 között lehet.',
    'Navigation supports at most 12 items.': 'A navigáció legfeljebb 12 elemet támogat.',
    'Every navigation item requires English and Hungarian labels.': 'Minden navigációs elemhez angol és magyar felirat szükséges.',
    'Navigation URLs must be internal paths or absolute HTTP(S) URLs.': 'A navigációs URL-ek belső útvonalak vagy teljes HTTP(S) URL-ek lehetnek.',
    'Navigation order values must be unique.': 'A navigáció sorrendértékeinek egyedinek kell lenniük.',
    'Language': 'Nyelv',
    'English (US)': 'Angol (USA)',
    'Magyar': 'Magyar',
    'Stable page key *': 'Stabil oldalkulcs *',
    'Page key, name and slug are required.': 'Az oldalkulcs, a név és a slug megadása kötelező.',
    'Versions': 'Verziók',
    'Preview token': 'Előnézeti token',
    'Not issued': 'Nincs kiadva',
    'Page key': 'Oldalkulcs',
  };

  static String literal(String locale, String value) {
    if (locale != 'hu_HU' || value.trim().isEmpty) return value;
    final exact = _literalHu[value] ?? _extendedHu[value] ?? _designHu[value];
    if (exact != null) return exact;

    String countLabel(String suffix, String translatedSuffix) {
      if (!value.endsWith(suffix)) return '';
      final raw = value.substring(0, value.length - suffix.length).trim();
      return int.tryParse(raw) == null ? '' : '$raw $translatedSuffix';
    }

    for (final pair in <List<String>>[
      [' partners', 'partner'],
      [' roles', 'szerepkör'],
      [' services', 'szolgáltatás'],
      [' reports', 'jelentés'],
      [' metrics', 'mérőszám'],
      [' leads', 'érdeklődő'],
    ]) {
      final translated = countLabel(pair[0], pair[1]);
      if (translated.isNotEmpty) return translated;
    }

    if (value.startsWith('Assigned: ')) {
      return 'Felelős: ${value.substring('Assigned: '.length)}';
    }
    if (value.startsWith('Navigation item ')) {
      return 'Navigációs elem ${value.substring('Navigation item '.length)}';
    }
    if (value.startsWith('Published ')) {
      return 'Publikálva: ${value.substring('Published '.length)}';
    }
    if (value.startsWith('Page ') && value.contains(' of ')) {
      final body = value.substring(5).split(' of ');
      if (body.length == 2) return '${body[0]} / ${body[1]} oldal';
    }

    var translated = value;
    for (final entry in _fallbackHu.entries) {
      translated = translated.replaceAll(entry.key, entry.value);
    }
    return translated;
  }

  static String text(String locale, String key) {
    final normalized = locale == 'hu_HU' ? 'hu_HU' : 'en_US';
    return _values[normalized]?[key] ?? _values['en_US']?[key] ?? key;
  }

  static String dateTime(String locale, DateTime value) {
    final tag = locale == 'hu_HU' ? 'hu_HU' : 'en_US';
    return intl.DateFormat.yMMMd(tag).add_Hm().format(value.toLocal());
  }

  static String currency(String locale, num value, {String currency = 'USD'}) {
    final tag = locale == 'hu_HU' ? 'hu_HU' : 'en_US';
    return intl.NumberFormat.simpleCurrency(locale: tag, name: currency).format(value);
  }
}

bool himatePasswordMeetsPolicy(String value) {
  if (value.runes.length < 12) return false;
  return RegExp(r'[a-z]').hasMatch(value) &&
      RegExp(r'[A-Z]').hasMatch(value) &&
      RegExp(r'[0-9]').hasMatch(value) &&
      RegExp(r'[^A-Za-z0-9\s]').hasMatch(value);
}

String? himatePasswordPolicyMessage(String locale, String value) =>
    himatePasswordMeetsPolicy(value) ? null : HimateI18n.text(locale, 'passwordPolicy');
